### ISSUE TITLE
Can't decompile files - bad magic

### ISSUE THREAD

**Issue by KhArtNJava** [zrax/pycdc#110]
Hello.

Can you look at these files? I can't decompile them.

Thank you!

[Debug.zip](https://github.com/zrax/pycdc/files/805065/Debug.zip)

**Comment by zrax** [comment]
The files look valid Python 3.3 and load fine.  You may have an outdated pycdc build if it doesn't recognize them.

**Comment by KhArtNJava** [comment]
Hello.
I tried pycdc, compiled with MS VS 2015 x32 from master branch of this repo.

**Comment by zrax** [comment]
I still can't reproduce this with the same compiler and configuration.  Please provide more details on how you built it and how you're running it...

**Comment by zrax** [comment]
Closing due to lack of response.  Please reopen if the issue is unresolved.
