### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by tysondogerz** [zrax/pycdc#131]
pip install git+https://github.com/zrax/pycdc.git
Pip install pycdc

Command "python setup.py egg_info" failed with error code 1 in C:\Users\CC\AppData\Local\Temp\pip-myq2dh_f-build\

**Comment by zrax** [comment]
pycdc is not a python project or module -- it's a C++ application which parses Python bytecode.  Therefore, it cannot be built with pip/easy_install/etc.

**Comment by tysondogerz** [comment]
Know how to decompile pyinstaller exe's?  https://stackoverflow.com/questions/47441287/how-to-decompile-pyinstaller-created-exe-and-get-source-code  Having trouble finding source code
