### ISSUE TITLE
__future__ unicode_literals 

### ISSUE THREAD

**Issue by rocky** [zrax/pycdc#141]
On Python 2.6 and 2.7
```
from __future__ import unicode_literals
a = 'a'
ba = b'a'
bb = b'b'
```
decompiles to: 
```from __future__ import unicode_literals
a = u'a'
ba = 'a'
bb = 'b'
```

**Comment by zrax** [comment]
This can be detected based on the `CO_FUTURE_UNICODE_LITERALS` code flag.

**Comment by rocky** [comment]
Ok. Thanks for the information. Good to see that this project hasn't been abandoned.
