### ISSUE TITLE
method names in Python 2.5 erroneously get  class prefix added

### ISSUE THREAD

**Issue by rocky** [zrax/pycdc#166]
```python
class FdfParser:
    def __IsWhiteSpace(self, Char):
        if Char in (0, 1):
            return True
        else:
            return False
```
when compiled in Python 2.5 and decompiled gives: 

```python
class FdfParser:
    
    def _FdfParser__IsWhiteSpace(self, Char):
        if Char in (0, 1):
            return True
        else:
            return False
````

The method name seems to have `_Fd_Parse__` erroneously prepended.

**Comment by zrax** [comment]
It looks like Python itself compiles functions that start with a double `__` with the mangled name...  Interestingly, the name of the code object itself is the original name without the prefix.  This should probably be checked when emitting functions.
