### ISSUE TITLE
Unsupported opcode: <255>

### ISSUE THREAD

**Issue by npilipovic86** [zrax/pycdc#173]
hi, i try to use pycdc, and gettin this error

Source Generated with Decompyle++
File: test.pyc (Python 2.7)

Unsupported opcode: <255>
WARNING: Decompyle incomplete

**Comment by AShedko** [comment]
255 is not a valid python opcode, see issue #98.
You are decompiling an obfuscated script.
See also:
https://github.com/python/cpython/blob/master/Lib/opcode.py

**Comment by zrax** [comment]
This issue can't be addressed without more information.  If you are certain your bytecode is not obfuscated, please provide more details (or an example) and reopen the issue.
