### ISSUE TITLE
Unsupported opcodes Python 3.9.4

### ISSUE THREAD

**Issue by dimonpanik** [zrax/pycdc#190]
Unsupported opcode: RERAISE
Unsupported opcode: LIST_EXTEND
Unsupported opcode: JUMP_IF_NOT_EXC_MATCH
Unsupported opcode: CONTAINS_OP
Unsupported opcode: CONTAINS_OP
Unsupported opcode: CONTAINS_OP
Unsupported opcode: LIST_EXTEND
Unsupported opcode: CONTAINS_OP
Unsupported opcode: CONTAINS_OP
Unsupported opcode: WITH_EXCEPT_START
Unsupported opcode: JUMP_IF_NOT_EXC_MATCH
Unsupported opcode: RERAISE
Unsupported opcode: CONTAINS_OP
Unsupported opcode: IS_OP
Unsupported opcode: JUMP_IF_NOT_EXC_MATCH
Unsupported opcode: JUMP_IF_NOT_EXC_MATCH
Unsupported opcode: JUMP_IF_NOT_EXC_MATCH
Unsupported opcode: CONTAINS_OP
Unsupported opcode: CONTAINS_OP
Segmentation fault (core dumped)

File 
[file.zip](https://github.com/zrax/pycdc/files/6323486/file.zip)

**Comment by SergioArrighi** [comment]
Hello, any ongoing activity to support JUMP_IF_NOT_EXC_MATCH and RERAISE?
Thanks and best regards

**Comment by Ahmed7fathi** [comment]
@dimonpanik can I ask your OS type?

**Comment by thegeicogecko** [comment]
Jumping in here to say I am also facing this issue and am on OSX Monterey running the M1 chip.

**Comment by dimonpanik** [comment]
> @dimonpanik can I ask your OS type?

Win 10

**Comment by zrax** [comment]
Duplicate #450
