### ISSUE TITLE
Pycdc

### ISSUE THREAD

**Issue by Tech-abm** [zrax/pycdc#194]
Good

**Comment by Hamayun123788** [comment]
> Hello,
> Make a new repo of decompile cython so file.
> Your pycdc repo is best and strong. It's support of all type python pyc Decompile . Now, can you guide me, how to decode cython so file using 32BIT and 64bit on termux emulator

hello abm bro pls delete this comments.

**Comment by hamayunpro** [comment]
hello bhai
script chahye muje
