### ISSUE TITLE
Fix : Unsupported opcode: RERAISE

### ISSUE THREAD

**Issue by expiren** [zrax/pycdc#210]
hello please fix Unsupported opcode: RERAISE

**Comment by Ezipsoft** [comment]
do you have any profress with this opcode ?

**Comment by knxxxy** [comment]
also facing this unsupported opcode - could share a .pyc which is affected

**Comment by wibuf** [comment]
This is still an issue, I'm seeing this as well

**Comment by tonyblackbird** [comment]
Hope the issue is fixed soon

**Comment by zrax** [comment]
Duplicate #450
