### ISSUE TITLE
Not working Error

### ISSUE THREAD

**Issue by TechQaiser** [zrax/pycdc#212]
![IMG-20211105-WA0010](https://user-images.githubusercontent.com/69212320/140411756-af52686f-95cc-4cc7-a0f9-3da373b6e662.jpg)

Why Pycdc Why Not Installing please Bro Update it fastly 😟

**Comment by zrax** [comment]
Is that termux?  Last I checked, you'll need to install the `binutils` package to get a working linker that CMake understands.  I haven't looked into why this broke recently, but I guess you'd have to ask the termux folks about that.

**Comment by TechQaiser** [comment]
> Is that termux? Last I checked, you'll need to install the `binutils` package to get a working linker that CMake understands. I haven't looked into why this broke recently, but I guess you'd have to ask the termux folks about that.

Bro So Where I run It Not In Termux So Where Can I Run It 😟

**Comment by TechQaiser** [comment]
So Where can i use this script Not Termux So Where 😟

**Comment by zrax** [comment]
I don't understand the question.  It works fine in termux, you just need to install `binutils` first (before running cmake), as I mentioned previously.
