### ISSUE TITLE
STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by cchgray2** [zrax/pycdc#216]
This is probably a pretty basic fix as I haven't used cpp in years, so please excuse the newbie question...
when I try to compile (with g++) I get this error:  Exception: STATUS_ACCESS_VIOLATION
[main] cc1plus 1002 (0) handle_exceptions: Dumping stack trace to cc1plus.exe.core. See below

When I try to just use ./pycdas [PATH TO PYC FILE], 'pycdas' is not recognized as an internal or external command,
operable program or batch file.

Any help would be appreciated! Thanks in advance

[main] cc1plus 1002 (0) exception: trapped!
[main] cc1plus 1002 (0) exception: code 0xC0000005 at 0x419603
[main] cc1plus 1002 (0) exception: ax 0xA bx 0x1 cx 0x0 dx 0x61061104
[main] cc1plus 1002 (0) exception: si 0x10F02E10 di 0x0 bp 0x45DF1B8 sp 0x45DF19C
[main] cc1plus 1002 (0) exception: exception is: STATUS_ACCESS_VIOLATION
[main] cc1plus 1002 (0) stack: Stack trace:
[main] cc1plus 1002 (0) stack: frame 0: sp = 0x45DED28, pc = 0x6100A2C3
[main] cc1plus 1002 (0) stack: frame 1: sp = 0x45DED64, pc = 0x76ECDEF2
[main] cc1plus 1002 (0) stack: frame 2: sp = 0x45DED88, pc = 0x76ECDEC4
[main] cc1plus 1002 (0) stack: frame 3: sp = 0x45DEE48, pc = 0x76EC7E06
[main] cc1plus 1002 (0) stack: frame 4: sp = 0x45DF1B8, pc = 0x412724
[main] cc1plus 1002 (0) stack: frame 5: sp = 0x45DF1F8, pc = 0x4178B7
[main] cc1plus 1002 (0) stack: frame 6: sp = 0x45DF2FC, pc = 0x41BEBD
[main] cc1plus 1002 (0) stack: frame 7: sp = 0x45DF31C, pc = 0x45D2A0
[main] cc1plus 1002 (0) stack: frame 8: sp = 0x45DFBF8, pc = 0x48FB85
[main] cc1plus 1002 (0) stack: frame 9: sp = 0x45DFC24, pc = 0x49328B
[main] cc1plus 1002 (0) stack: frame 10: sp = 0x45DFC7C, pc = 0x61004402
[main] cc1plus 1002 (0) stack: frame 11: sp = 0x45DFEA0, pc = 0x61004420
[main] cc1plus 1002 (0) stack: frame 12: sp = 0x45DFEAC, pc = 0x5B26CE
[main] cc1plus 1002 (0) stack: frame 13: sp = 0x45DFEBC, pc = 0x40103A
[main] cc1plus 1002 (0) stack: frame 14: sp = 0x45DFED8, pc = 0x759F5BD8
[main] cc1plus 1002 (0) stack: frame 15: sp = 0x45DFEF0, pc = 0x7595D6FC
[main] cc1plus 1002 (0) stack: End of stack trace (more stack frames may be present)

**Comment by cchgray2** [comment]
cmake, eh

**Comment by Zinzslol** [comment]
how u fix it
