### ISSUE TITLE
Can someone please tell me how to make it run it? humanreadable

### ISSUE THREAD

**Issue by AlexWayne20** [zrax/pycdc#222]
i dont understand how to "Generate a project or makefile with CMake". google doesnt help and cmake documentation.

im trying to do it in pyhton on visual studio code windows. so what do i need? 

please can you share a good guide how to do it? 

for someone who is new in programming cant understand that, please translate in humanreadable:

Generate a project or makefile with CMake (See CMake's documentation for details)
The following options can be passed to CMake to control debug features:
Build the generated project or makefile
For projects (e.g. MSVC), open the generated project file and build it
For makefiles, just run make
To run tests (on *nix or MSYS), run make check

**Comment by Kraysh** [comment]
```
apt install cmake
cmake .
make
```
