### ISSUE TITLE
Inconsistent error log location and format

### ISSUE THREAD

**Issue by CaledoniaProject** [zrax/pycdc#224]
I just noticed pycdc does not have a uniformed logger,

Some of those errors does not start with a comment, e.g

```
default:
            fprintf(stderr, "Unsupported opcode: %s\n", Pyc::OpcodeName(opcode & 0xFF));
            cleanBuild = false;
            return new ASTNodeList(defblock->nodes());
        }
```

This seems to be the only one starts with a comment:

```
if (!cleanBuild || !part1clean) {
        start_line(cur_indent);
        fputs("# WARNING: Decompyle incomplete\n", pyc_output);
    }
```

Why won't you place a `#` before all those logs?

**Comment by zrax** [comment]
There's a key difference between the two:  One is output to stderr (which means it won't get redirected to your output file, and therefore doesn't need to be valid Python syntax) and the other is output to the output stream (i.e. your output file, which must be Python compatible).

**Comment by CaledoniaProject** [comment]
Thanks!
