### ISSUE TITLE
Bad MAGIC! ok.pyc (Python -1.-1) <NULL>%               

### ISSUE THREAD

**Issue by scz-u** [zrax/pycdc#228]
python3.95

# WARNING: Decompyle incomplete

**Comment by Marshallsus** [comment]
This is a problem on your side. "Bad MAGIC"

**Comment by lilechao** [comment]
However, some code will be decompiled, and some will prompt warning: decode incomplete. How do I deal with this

**Comment by lilechao** [comment]
![image](https://user-images.githubusercontent.com/12441041/146473485-8c462c47-17ba-42d5-9114-535bb561d2c2.png)

**Comment by hossainimamrony** [comment]
Bad MAGIC!
Could not load file

HOw to solve this problem???

**Comment by zrax** [comment]
Duplicate #450
