### ISSUE TITLE
How to get original number?

### ISSUE THREAD

**Issue by StiKipeT** [zrax/pycdc#237]
decompiled code -
`b = 0xA8A1591141E5L`

original code - 
`b = 185410937504229`

**Comment by Deledrius** [comment]
Those numbers are the same value, the first is represented in hexadecimal, the second in decimal.  There's no way for the decompyler to know which representation was used in the original code because that information is not stored in the bytecode, only the value of the number itself.

**Comment by StiKipeT** [comment]
> 

can a hexadecimal string contain L?

**Comment by StiKipeT** [comment]
but small numbers like 123 can by decompiled

**Comment by zrax** [comment]
The `L` suffix means it's a `long` (vs. an `int`; the difference is that `long` can be any arbitrary size whereas an int is limited to 32-bits).  pycdc prints `long`s in hex (for technical laziness reasons) and `int`s in decimal.  As @Deledrius pointed out, the values are identical, and pycdc has no way of knowing what base was used in the original source.
