### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by HiMark146** [zrax/pycdc#261]
Hi, in the 'pycdc-master' folder, I ran this command:
python pycdc C:\Users\Rollo\Desktop\decompile\Test.pyc

But this error keeps appearing:
[Errno 2] No such file or directory

Can you help me?

**Comment by jaiakash** [comment]
Its a .cpp program not a python script.
```.\pycdc.cpp C:\Users\Rollo\Desktop\decompile\Test.pyc``` should work.
Let me know if it doesnt work.

**Comment by zrax** [comment]
pycdc is a compiled C++ application, not a Python script.  You will need to build it as described in the Readme (https://github.com/zrax/pycdc#building-decompyle) and then run the generated executable.
