### ISSUE TITLE
The C compiler identification is unknown

### ISSUE THREAD

**Issue by redbaron2k7** [zrax/pycdc#264]
-- Selecting Windows SDK version  to target Windows 10.0.19044.
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!
See also "C:/Users/test/pycdc/CMakeFiles/CMakeOutput.log".
See also "C:/Users/test/pycdc/CMakeFiles/CMakeError.log"

**Comment by ptrstr** [comment]
You need to install Visual Studio or launch CMake from the VS Developer Console
