### ISSUE TITLE
Unsupported opcode: <255>

### ISSUE THREAD

**Issue by makitos666** [zrax/pycdc#271]
I'm analysing an obfuscated python script with PyArmor using python 3.10.

To do it, I modified the source code of PyEval_EvalCode to marshal and download de code before evaluating it.

Python seems that it's ok with the bytecode, because it's executing it. But pycdc says this:
(all other bytecodes not directly refered with PyArmor are correctly decompiled)
```
# Source Generated with Decompyle++
# File: 18.BC (Python 3.10)

Unsupported opcode: <255>
return __armor_wrap__()
# WARNING: Decompyle incomplete
```

**Comment by zrax** [comment]
Obfuscated bytecode is currently outside the scope of pycdc...  You'll need to either de-obfuscate it first or try a different decompiler.
