### ISSUE TITLE
Disassembler/Decompiler

### ISSUE THREAD

**Issue by Intellbg** [zrax/pycdc#273]
Why I am able to use pycdas with my file, but when pycdas is used i got the following error. 
 
```
 # Source Generated with Decompyle++
# File: siemensExtractor.pyc (Python 3.9)

Unsupported opcode: <255>
from os.path import exists
from datetime import datetime
import json
import os
import pandas as pd
import requests
import io
# WARNING: Decompyle incomplete
```

**Comment by ahaensler** [comment]
Decompilation doesn't really work for versions >= 3.8. There is new opcodes and compiler output got more efficient/dense. You could try python 3.7, or look at my [PR](https://github.com/zrax/pycdc/pull/270) that fixes for loops in 3.8
