### ISSUE TITLE
decompile pyc into py

### ISSUE THREAD

**Issue by angelheart150** [zrax/pycdc#280]
i can't decompile this file from pyc into py 
please help how can i do this ?
![Screenshot from 2022-09-12 22-35-14](https://user-images.githubusercontent.com/67199651/190595671-706b1b44-6538-4a44-8a55-c99df539e999.png)
[PluginBrowser.zip](https://github.com/zrax/pycdc/files/9582246/PluginBrowser.zip)

**Comment by 0x3C50** [comment]
wrong project
