### ISSUE TITLE
Unsupported opcode: GEN_START

### ISSUE THREAD

**Issue by HideakiAtsuyo** [zrax/pycdc#286]
Hello, from what I see [This](https://github.com/zrax/pycdc/blob/master/PythonBytecode.txt#L671) & [This](https://github.com/zrax/pycdc/blob/master/bytecode_ops.inl#L142) the GEN_START opcode should be supported ? Or did I miss something ?

Apparently It's not supported for Python 3.10, have you any info on how I can add the support of this opcode to pycdc ?
Or can you add it ?

**Comment by RadonCoding** [comment]
gay

**Comment by HideakiAtsuyo** [comment]
> gay

Gay stalker😔
