### ISSUE TITLE
SyntaxError: Non-UTF-8 code...

### ISSUE THREAD

**Issue by BlueBerrySans365** [zrax/pycdc#288]
After building from source it shows this:
```
SyntaxError: Non-UTF-8 code starting with '\x8a' in file /home/nicksalt/Downloads/bruh/build/pycdc on line 3, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details
```
Using Arch Linux + Python 3.10.7

**Comment by bstudiosoriginal** [comment]
Run with
./pycdc '/path/to/pyc'

Obviously replacing '/path/to/pyc' with the actual path to .pyc file.

**Comment by nitrag** [comment]
For met it had to be an absolute path. `~/` relative was causing that error
