### ISSUE TITLE
Unsupported opcode: JUMP_IF_NOT_EXC_MATCH

### ISSUE THREAD

**Issue by ghost** [zrax/pycdc#292]
When I want Decompile Any File It Says That

Unsupported opcode: JUMP_IF_NOT_EXC_MATCH
# WARNING: Decompyle incomplete

Please How I Can Fix That please help me

**Comment by CoverDisc** [comment]
it's the same error from pycfile python 3.10.4

**Comment by Zejzz** [comment]
anyone got a fix for this?

**Comment by zrax** [comment]
Duplicate #450
