### ISSUE TITLE
pycdc: command not found

### ISSUE THREAD

**Issue by rrblgn** [zrax/pycdc#296]
I followed the steps: cloned the github repo, created a cmake project and made it successfuly, i.e. without any error, however when it comes to run pycdc, I encounter : "pycdc: command not found"

**Comment by p4kl0nc4t** [comment]
You have to run it this way.

```
$ cd path_to_cloned_repo
$ ./pycdc
```

**Comment by ToneXum** [comment]
Hey Man, I tried using the prefixes you provided.
It still didnt work : /

**Comment by brookslach** [comment]
CD to the directory where the executables are and run according to your OS:
Windows: pycdc.exe
Unix: ./pycdc
