### ISSUE TITLE
 SyntaxError: Non-ASCII character '\x8a' in file pycdc on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

### ISSUE THREAD

**Issue by oHeckGage** [zrax/pycdc#299]
Whenever I run python3.10 pycdc aurora.pyc (the file I'm trying to decompile), it shows this error after using [this](https://stackoverflow.com/questions/71278961/how-can-i-decompile-pyc-files-from-python-3-10) StackOverFlow tutorial to setup pycdc.

Is there something wrong with that tutorial, is python3.10 not supported, or am I doing something wrong?

**Comment by zrax** [comment]
pycdc is not a python script, it's a native executable (after compiling it).  You'll want to run it directly, not with python.
