### ISSUE TITLE
# WARNING: Decompyle incomplete

### ISSUE THREAD

**Issue by trcmzng** [zrax/pycdc#308]
during decompilation, # Decompile 'RERAISE' is not implemented yet.
Unsupported opcode: JUMP_IF_NOT_EXC_MATCHб then only part of the code was recognized, and then # WARNING: Decompyle incomplete how to fix

**Comment by TheHellTower** [comment]
> during decompilation, # Decompile 'RERAISE' is not implemented yet. Unsupported opcode: JUMP_IF_NOT_EXC_MATCHб then only part of the code was recognized, and then # WARNING: Decompyle incomplete how to fix

I forked this repo it seems a little abandoned.

So you can check [this issue](https://github.com/TheHellTower/pycdc/issues/1) and read the note to help in fixing these missing opcodes.

Each missing opcode following the note steps will be fixed as soon as possible.

Thanks for your help.

**Comment by zrax** [comment]
Duplicate #450
