### ISSUE TITLE
PUSH_NULL

### ISSUE THREAD

**Issue by divyamrajput** [zrax/pycdc#322]
====> [Hi.zip] (https://github.com/zrax/pycdc/files/10797905/Hi.zip)

# Source Generated with Decompyle++
# File: hi.pyc (Python 3.11)

Unsupported opcode: PUSH_NULL
import marshal
# WARNING: Decompyle incomplete

How to fix this Help

**Comment by TheHellTower** [comment]
> ====> [Hi.zip] (https://github.com/zrax/pycdc/files/10797905/Hi.zip)
> 
> # Source Generated with Decompyle++
> # File: hi.pyc (Python 3.11)
> Unsupported opcode: PUSH_NULL import marshal
> 
> # WARNING: Decompyle incomplete
> How to fix this Help

Hello, I verified the file and updated pycdc on my side and after adding [`PUSH_NULL`](https://docs.python.org/3/library/dis.html#opcode-PUSH_NULL) there are still [`PRECALL`](https://docs.python.org/3/library/dis.html#opcode-PRECALL) and [`CALL`](https://docs.python.org/3/library/dis.html#opcode-CALL) if not more I will try to finish the update soon to push it as soon as possible.

Regards.

**Comment by divyamrajput** [comment]
> > ====> [Hi.zip] (https://github.com/zrax/pycdc/files/10797905/Hi.zip)
> > # Source Generated with Decompyle++
> > # File: hi.pyc (Python 3.11)
> > Unsupported opcode: PUSH_NULL import marshal
> > # WARNING: Decompyle incomplete
> > How to fix this Help
> 
> Hello, I verified the file and updated pycdc on my side and after adding [`PUSH_NULL`](https://docs.python.org/3/library/dis.html#opcode-PUSH_NULL) there are still [`PRECALL`](https://docs.python.org/3/library/dis.html#opcode-PRECALL) and [`CALL`](https://docs.python.org/3/library/dis.html#opcode-CALL) if not more I will try to finish the update soon to push it as soon as possible.
> 
> Regards.

Ok Sir Thankyou so much.

**Comment by TheHellTower** [comment]
> > > ====> [Hi.zip] (https://github.com/zrax/pycdc/files/10797905/Hi.zip)
> > > # Source Generated with Decompyle++
> > > # File: hi.pyc (Python 3.11)
> > > Unsupported opcode: PUSH_NULL import marshal
> > > # WARNING: Decompyle incomplete
> > > How to fix this Help
> > 
> > 
> > Hello, I verified the file and updated pycdc on my side and after adding [`PUSH_NULL`](https://docs.python.org/3/library/dis.html#opcode-PUSH_NULL) there are still [`PRECALL`](https://docs.python.org/3/library/dis.html#opcode-PRECALL) and [`CALL`](https://docs.python.org/3/library/dis.html#opcode-CALL) if not more I will try to finish the update soon to push it as soon as possible.
> > Regards.
> 
> Ok Sir Thankyou so much.

I'm there for the moment I'm not sure why you imported marshal 2 times but I'm close: ![](https://i.imgur.com/JYIUpz0.png)

**Comment by divyamrajput** [comment]
> > > > ====> [Hi.zip] (https://github.com/zrax/pycdc/files/10797905/Hi.zip)
> > > > # Source Generated with Decompyle++
> > > > # File: hi.pyc (Python 3.11)
> > > > Unsupported opcode: PUSH_NULL import marshal
> > > > # WARNING: Decompyle incomplete
> > > > How to fix this Help
> > > 
> > > 
> > > Hello, I verified the file and updated pycdc on my side and after adding [`PUSH_NULL`](https://docs.python.org/3/library/dis.html#opcode-PUSH_NULL) there are still [`PRECALL`](https://docs.python.org/3/library/dis.html#opcode-PRECALL) and [`CALL`](https://docs.python.org/3/library/dis.html#opcode-CALL) if not more I will try to finish the update soon to push it as soon as possible.
> > > Regards.
> > 
> > 
> > Ok Sir Thankyou so much.
> 
> I'm there for the moment I'm not sure why you imported marshal 2 times but I'm close: ![](https://camo.githubusercontent.com/95d5cd239e01a9bb5039498f771d9757c4f92e1b2c1c8ceb1089e04a1354a29e/68747470733a2f2f692e696d6775722e636f6d2f4a594955707a302e706e67)

Ohh sorry broh , i was in fast when i encrypting this. But try to decode marshal till last. Untill source code.

**Comment by TheHellTower** [comment]
> > > > > ====> [Hi.zip] (https://github.com/zrax/pycdc/files/10797905/Hi.zip)
> > > > > # Source Generated with Decompyle++
> > > > > # File: hi.pyc (Python 3.11)
> > > > > Unsupported opcode: PUSH_NULL import marshal
> > > > > # WARNING: Decompyle incomplete
> > > > > How to fix this Help
> > > > 
> > > > 
> > > > Hello, I verified the file and updated pycdc on my side and after adding [`PUSH_NULL`](https://docs.python.org/3/library/dis.html#opcode-PUSH_NULL) there are still [`PRECALL`](https://docs.python.org/3/library/dis.html#opcode-PRECALL) and [`CALL`](https://docs.python.org/3/library/dis.html#opcode-CALL) if not more I will try to finish the update soon to push it as soon as possible.
> > > > Regards.
> > > 
> > > 
> > > Ok Sir Thankyou so much.
> > 
> > 
> > I'm there for the moment I'm not sure why you imported marshal 2 times but I'm close: ![](https://camo.githubusercontent.com/95d5cd239e01a9bb5039498f771d9757c4f92e1b2c1c8ceb1089e04a1354a29e/68747470733a2f2f692e696d6775722e636f6d2f4a594955707a302e706e67)
> 
> Ohh sorry broh , i was in fast when i encrypting this. But try to decode marshal till last. Untill source code.

The goal of pycdc is only to decompyle your file bytecodes not the bytecodes inside a potential script so that's not what you should expect

**Comment by divyamrajput** [comment]
> 

Okay bro but how you fix push_null error

**Comment by divyamrajput** [comment]
> > > > > > ====> [Hi.zip] (https://github.com/zrax/pycdc/files/10797905/Hi.zip)
> > > > > > # Source Generated with Decompyle++
> > > > > > # File: hi.pyc (Python 3.11)
> > > > > > Unsupported opcode: PUSH_NULL import marshal
> > > > > > # WARNING: Decompyle incomplete
> > > > > > How to fix this Help
> > > > > 
> > > > > 
> > > > > Hello, I verified the file and updated pycdc on my side and after adding [`PUSH_NULL`](https://docs.python.org/3/library/dis.html#opcode-PUSH_NULL) there are still [`PRECALL`](https://docs.python.org/3/library/dis.html#opcode-PRECALL) and [`CALL`](https://docs.python.org/3/library/dis.html#opcode-CALL) if not more I will try to finish the update soon to push it as soon as possible.
> > > > > Regards.
> > > > 
> > > > 
> > > > Ok Sir Thankyou so much.
> > > 
> > > 
> > > I'm there for the moment I'm not sure why you imported marshal 2 times but I'm close: ![](https://camo.githubusercontent.com/95d5cd239e01a9bb5039498f771d9757c4f92e1b2c1c8ceb1089e04a1354a29e/68747470733a2f2f692e696d6775722e636f6d2f4a594955707a302e706e67)
> > 
> > 
> > Ohh sorry broh , i was in fast when i encrypting this. But try to decode marshal till last. Untill source code.
> 
> The goal of pycdc is only to decompyle your file bytecodes not the bytecodes inside a potential script so that's not what you should expect

Okay bro thanks you so much please tell me how you fix push_null error

**Comment by TheHellTower** [comment]
> > > > > > > ====> [Hi.zip] (https://github.com/zrax/pycdc/files/10797905/Hi.zip)
> > > > > > > # Source Generated with Decompyle++
> > > > > > > # File: hi.pyc (Python 3.11)
> > > > > > > Unsupported opcode: PUSH_NULL import marshal
> > > > > > > # WARNING: Decompyle incomplete
> > > > > > > How to fix this Help
> > > > > > 
> > > > > > 
> > > > > > Hello, I verified the file and updated pycdc on my side and after adding [`PUSH_NULL`](https://docs.python.org/3/library/dis.html#opcode-PUSH_NULL) there are still [`PRECALL`](https://docs.python.org/3/library/dis.html#opcode-PRECALL) and [`CALL`](https://docs.python.org/3/library/dis.html#opcode-CALL) if not more I will try to finish the update soon to push it as soon as possible.
> > > > > > Regards.
> > > > > 
> > > > > 
> > > > > Ok Sir Thankyou so much.
> > > > 
> > > > 
> > > > I'm there for the moment I'm not sure why you imported marshal 2 times but I'm close: ![](https://camo.githubusercontent.com/95d5cd239e01a9bb5039498f771d9757c4f92e1b2c1c8ceb1089e04a1354a29e/68747470733a2f2f692e696d6775722e636f6d2f4a594955707a302e706e67)
> > > 
> > > 
> > > Ohh sorry broh , i was in fast when i encrypting this. But try to decode marshal till last. Untill source code.
> > 
> > 
> > The goal of pycdc is only to decompyle your file bytecodes not the bytecodes inside a potential script so that's not what you should expect
> 
> Okay bro thanks you so much please tell me how you fix push_null error

I will open a PR if I can fix all the needed opcodes for this script.

**Comment by divyamrajput** [comment]
> > > > > > > > ====> [Hi.zip] (https://github.com/zrax/pycdc/files/10797905/Hi.zip)
> > > > > > > > # Source Generated with Decompyle++
> > > > > > > > # File: hi.pyc (Python 3.11)
> > > > > > > > Unsupported opcode: PUSH_NULL import marshal
> > > > > > > > # WARNING: Decompyle incomplete
> > > > > > > > How to fix this Help
> > > > > > > 
> > > > > > > 
> > > > > > > Hello, I verified the file and updated pycdc on my side and after adding [`PUSH_NULL`](https://docs.python.org/3/library/dis.html#opcode-PUSH_NULL) there are still [`PRECALL`](https://docs.python.org/3/library/dis.html#opcode-PRECALL) and [`CALL`](https://docs.python.org/3/library/dis.html#opcode-CALL) if not more I will try to finish the update soon to push it as soon as possible.
> > > > > > > Regards.
> > > > > > 
> > > > > > 
> > > > > > Ok Sir Thankyou so much.
> > > > > 
> > > > > 
> > > > > I'm there for the moment I'm not sure why you imported marshal 2 times but I'm close: ![](https://camo.githubusercontent.com/95d5cd239e01a9bb5039498f771d9757c4f92e1b2c1c8ceb1089e04a1354a29e/68747470733a2f2f692e696d6775722e636f6d2f4a594955707a302e706e67)
> > > > 
> > > > 
> > > > Ohh sorry broh , i was in fast when i encrypting this. But try to decode marshal till last. Untill source code.
> > > 
> > > 
> > > The goal of pycdc is only to decompyle your file bytecodes not the bytecodes inside a potential script so that's not what you should expect
> > 
> > 
> > Okay bro thanks you so much please tell me how you fix push_null error
> 
> I will open a PR if I can fix all the needed opcodes for this script.

Yeah, okay bro ❤️

**Comment by TheHellTower** [comment]
> > > > > > > > > ====> [Hi.zip] (https://github.com/zrax/pycdc/files/10797905/Hi.zip)
> > > > > > > > > # Source Generated with Decompyle++
> > > > > > > > > # File: hi.pyc (Python 3.11)
> > > > > > > > > Unsupported opcode: PUSH_NULL import marshal
> > > > > > > > > # WARNING: Decompyle incomplete
> > > > > > > > > How to fix this Help
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Hello, I verified the file and updated pycdc on my side and after adding [`PUSH_NULL`](https://docs.python.org/3/library/dis.html#opcode-PUSH_NULL) there are still [`PRECALL`](https://docs.python.org/3/library/dis.html#opcode-PRECALL) and [`CALL`](https://docs.python.org/3/library/dis.html#opcode-CALL) if not more I will try to finish the update soon to push it as soon as possible.
> > > > > > > > Regards.
> > > > > > > 
> > > > > > > 
> > > > > > > Ok Sir Thankyou so much.
> > > > > > 
> > > > > > 
> > > > > > I'm there for the moment I'm not sure why you imported marshal 2 times but I'm close: ![](https://camo.githubusercontent.com/95d5cd239e01a9bb5039498f771d9757c4f92e1b2c1c8ceb1089e04a1354a29e/68747470733a2f2f692e696d6775722e636f6d2f4a594955707a302e706e67)
> > > > > 
> > > > > 
> > > > > Ohh sorry broh , i was in fast when i encrypting this. But try to decode marshal till last. Untill source code.
> > > > 
> > > > 
> > > > The goal of pycdc is only to decompyle your file bytecodes not the bytecodes inside a potential script so that's not what you should expect
> > > 
> > > 
> > > Okay bro thanks you so much please tell me how you fix push_null error
> > 
> > 
> > I will open a PR if I can fix all the needed opcodes for this script.
> 
> Yeah, okay bro ❤️

![](https://i.imgur.com/cmg1PFT.png)<br>![](https://i.imgur.com/I7B5m9v.png)<br>I'm going to open a PR but it will probably need further verifications.

**Comment by divyamrajput** [comment]
> 


Yes , bro you are right. 👍

**Comment by divyamrajput** [comment]
> > > > > > > > > ====> [Hi.zip] (https://github.com/zrax/pycdc/files/10797905/Hi.zip)
> > > > > > > > > # Source Generated with Decompyle++
> > > > > > > > > # File: hi.pyc (Python 3.11)
> > > > > > > > > Unsupported opcode: PUSH_NULL import marshal
> > > > > > > > > # WARNING: Decompyle incomplete
> > > > > > > > > How to fix this Help
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Hello, I verified the file and updated pycdc on my side and after adding [`PUSH_NULL`](https://docs.python.org/3/library/dis.html#opcode-PUSH_NULL) there are still [`PRECALL`](https://docs.python.org/3/library/dis.html#opcode-PRECALL) and [`CALL`](https://docs.python.org/3/library/dis.html#opcode-CALL) if not more I will try to finish the update soon to push it as soon as possible.
> > > > > > > > Regards.
> > > > > > > 
> > > > > > > 
> > > > > > > Ok Sir Thankyou so much.
> > > > > > 
> > > > > > 
> > > > > > I'm there for the moment I'm not sure why you imported marshal 2 times but I'm close: ![](https://camo.githubusercontent.com/95d5cd239e01a9bb5039498f771d9757c4f92e1b2c1c8ceb1089e04a1354a29e/68747470733a2f2f692e696d6775722e636f6d2f4a594955707a302e706e67)
> > > > > 
> > > > > 
> > > > > Ohh sorry broh , i was in fast when i encrypting this. But try to decode marshal till last. Untill source code.
> > > > 
> > > > 
> > > > The goal of pycdc is only to decompyle your file bytecodes not the bytecodes inside a potential script so that's not what you should expect
> > > 
> > > 
> > > Okay bro thanks you so much please tell me how you fix push_null error
> > 
> > 
> > I will open a PR if I can fix all the needed opcodes for this script.
> 
> Yeah, okay bro ❤️



> 

Yes bro you are right

**Comment by divyamrajput** [comment]
> > > > > > > > > > ====> [Hi.zip] (https://github.com/zrax/pycdc/files/10797905/Hi.zip)
> > > > > > > > > > # Source Generated with Decompyle++
> > > > > > > > > > # File: hi.pyc (Python 3.11)
> > > > > > > > > > Unsupported opcode: PUSH_NULL import marshal
> > > > > > > > > > # WARNING: Decompyle incomplete
> > > > > > > > > > How to fix this Help
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Hello, I verified the file and updated pycdc on my side and after adding [`PUSH_NULL`](https://docs.python.org/3/library/dis.html#opcode-PUSH_NULL) there are still [`PRECALL`](https://docs.python.org/3/library/dis.html#opcode-PRECALL) and [`CALL`](https://docs.python.org/3/library/dis.html#opcode-CALL) if not more I will try to finish the update soon to push it as soon as possible.
> > > > > > > > > Regards.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Ok Sir Thankyou so much.
> > > > > > > 
> > > > > > > 
> > > > > > > I'm there for the moment I'm not sure why you imported marshal 2 times but I'm close: ![](https://camo.githubusercontent.com/95d5cd239e01a9bb5039498f771d9757c4f92e1b2c1c8ceb1089e04a1354a29e/68747470733a2f2f692e696d6775722e636f6d2f4a594955707a302e706e67)
> > > > > > 
> > > > > > 
> > > > > > Ohh sorry broh , i was in fast when i encrypting this. But try to decode marshal till last. Untill source code.
> > > > > 
> > > > > 
> > > > > The goal of pycdc is only to decompyle your file bytecodes not the bytecodes inside a potential script so that's not what you should expect
> > > > 
> > > > 
> > > > Okay bro thanks you so much please tell me how you fix push_null error
> > > 
> > > 
> > > I will open a PR if I can fix all the needed opcodes for this script.
> > 
> > 
> > Yeah, okay bro ❤️
> 
> ![](https://camo.githubusercontent.com/8ad8c66c3aed1405a63a7d97d23cd69f2d8daefefc40750cc9d8990aa2291821/68747470733a2f2f692e696d6775722e636f6d2f636d67315046542e706e67)![](https://camo.githubusercontent.com/dde4060b2e75c2527ce1d3ce5da6886a82abca45031682825f84a57f8a091d51/68747470733a2f2f692e696d6775722e636f6d2f493742356d39762e706e67)I'm going to open a PR but it will probably need further verifications.

Can you share me this pycdc.exe code with me

**Comment by TheHellTower** [comment]
> > > > > > > > > > > ====> [Hi.zip] (https://github.com/zrax/pycdc/files/10797905/Hi.zip)
> > > > > > > > > > > # Source Generated with Decompyle++
> > > > > > > > > > > # File: hi.pyc (Python 3.11)
> > > > > > > > > > > Unsupported opcode: PUSH_NULL import marshal
> > > > > > > > > > > # WARNING: Decompyle incomplete
> > > > > > > > > > > How to fix this Help
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Hello, I verified the file and updated pycdc on my side and after adding [`PUSH_NULL`](https://docs.python.org/3/library/dis.html#opcode-PUSH_NULL) there are still [`PRECALL`](https://docs.python.org/3/library/dis.html#opcode-PRECALL) and [`CALL`](https://docs.python.org/3/library/dis.html#opcode-CALL) if not more I will try to finish the update soon to push it as soon as possible.
> > > > > > > > > > Regards.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Ok Sir Thankyou so much.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I'm there for the moment I'm not sure why you imported marshal 2 times but I'm close: ![](https://camo.githubusercontent.com/95d5cd239e01a9bb5039498f771d9757c4f92e1b2c1c8ceb1089e04a1354a29e/68747470733a2f2f692e696d6775722e636f6d2f4a594955707a302e706e67)
> > > > > > > 
> > > > > > > 
> > > > > > > Ohh sorry broh , i was in fast when i encrypting this. But try to decode marshal till last. Untill source code.
> > > > > > 
> > > > > > 
> > > > > > The goal of pycdc is only to decompyle your file bytecodes not the bytecodes inside a potential script so that's not what you should expect
> > > > > 
> > > > > 
> > > > > Okay bro thanks you so much please tell me how you fix push_null error
> > > > 
> > > > 
> > > > I will open a PR if I can fix all the needed opcodes for this script.
> > > 
> > > 
> > > Yeah, okay bro ❤️
> > 
> > 
> > ![](https://camo.githubusercontent.com/8ad8c66c3aed1405a63a7d97d23cd69f2d8daefefc40750cc9d8990aa2291821/68747470733a2f2f692e696d6775722e636f6d2f636d67315046542e706e67)![](https://camo.githubusercontent.com/dde4060b2e75c2527ce1d3ce5da6886a82abca45031682825f84a57f8a091d51/68747470733a2f2f692e696d6775722e636f6d2f493742356d39762e706e67)I'm going to open a PR but it will probably need further verifications.
> 
> Can you share me this pycdc.exe code with me

#324

**Comment by divyamrajput** [comment]
> > > > > > > > > > > > ====> [Hi.zip] (https://github.com/zrax/pycdc/files/10797905/Hi.zip)
> > > > > > > > > > > > # Source Generated with Decompyle++
> > > > > > > > > > > > # File: hi.pyc (Python 3.11)
> > > > > > > > > > > > Unsupported opcode: PUSH_NULL import marshal
> > > > > > > > > > > > # WARNING: Decompyle incomplete
> > > > > > > > > > > > How to fix this Help
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > Hello, I verified the file and updated pycdc on my side and after adding [`PUSH_NULL`](https://docs.python.org/3/library/dis.html#opcode-PUSH_NULL) there are still [`PRECALL`](https://docs.python.org/3/library/dis.html#opcode-PRECALL) and [`CALL`](https://docs.python.org/3/library/dis.html#opcode-CALL) if not more I will try to finish the update soon to push it as soon as possible.
> > > > > > > > > > > Regards.
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Ok Sir Thankyou so much.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > I'm there for the moment I'm not sure why you imported marshal 2 times but I'm close: ![](https://camo.githubusercontent.com/95d5cd239e01a9bb5039498f771d9757c4f92e1b2c1c8ceb1089e04a1354a29e/68747470733a2f2f692e696d6775722e636f6d2f4a594955707a302e706e67)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Ohh sorry broh , i was in fast when i encrypting this. But try to decode marshal till last. Untill source code.
> > > > > > > 
> > > > > > > 
> > > > > > > The goal of pycdc is only to decompyle your file bytecodes not the bytecodes inside a potential script so that's not what you should expect
> > > > > > 
> > > > > > 
> > > > > > Okay bro thanks you so much please tell me how you fix push_null error
> > > > > 
> > > > > 
> > > > > I will open a PR if I can fix all the needed opcodes for this script.
> > > > 
> > > > 
> > > > Yeah, okay bro ❤️
> > > 
> > > 
> > > ![](https://camo.githubusercontent.com/8ad8c66c3aed1405a63a7d97d23cd69f2d8daefefc40750cc9d8990aa2291821/68747470733a2f2f692e696d6775722e636f6d2f636d67315046542e706e67)![](https://camo.githubusercontent.com/dde4060b2e75c2527ce1d3ce5da6886a82abca45031682825f84a57f8a091d51/68747470733a2f2f692e696d6775722e636f6d2f493742356d39762e706e67)I'm going to open a PR but it will probably need further verifications.
> > 
> > 
> > Can you share me this pycdc.exe code with me
> 
> You can check the following pull request: #324
> 
> But I don't warranty it to be stable and perfect, I suggested a review in the PR before merging.

Okay bro thanks for helping, i checking...

**Comment by TheHellTower** [comment]
Some situations was badly handled I suggest you to use the last version of the code in the PR it should be merged soon.
