### ISSUE TITLE
Unsupported opcode: GEN_START

### ISSUE THREAD

**Issue by SkitrowGames** [zrax/pycdc#329]
I got this error.
[playbux.pyc.txt](https://github.com/zrax/pycdc/files/10875193/playbux.pyc.txt)

**Comment by SkitrowGames** [comment]
@TheHellTower

**Comment by TheHellTower** [comment]
> @TheHellTower

Hello,

I can't accept this, it is a actual script and not a sample.
Mention me again when you will have a real sample.

Regards.

**Comment by SkitrowGames** [comment]
[main.txt](https://github.com/zrax/pycdc/files/10876210/main.txt)

**Comment by SkitrowGames** [comment]
Got this @TheHellTower

**Comment by TheHellTower** [comment]
> Got this @TheHellTower

Well I will be more clear, It doesn't matter if the sample is a script or compiled but it has to be a real sample not a script you just want to get the source from.

**Comment by SkitrowGames** [comment]
What does mean sample? I have error specifically with this script, with others all is ok

**Comment by SkitrowGames** [comment]
> > Got this @TheHellTower
> 
> Well I will be more clear, It doesn't matter if the sample is a script or compiled but it has to be a real sample not a script you just want to get the source from.

What does mean sample? I have error specifically with this script, with others all is ok

**Comment by TheHellTower** [comment]
You can see a list of sample for supported opcodes [here](https://github.com/zrax/pycdc/tree/master/tests/input) (file name mean it got used for the opcode for example `gen_start.txt` would mean the file has been used for `gen_start` opcode support)

**Comment by SkitrowGames** [comment]
> 
[async_def.txt](https://github.com/zrax/pycdc/files/10876308/async_def.txt)
Like this?

**Comment by TheHellTower** [comment]
No. I assume you didn't even read the script in the `async_def.txt` file.

The samples need to be minimalist and not be a actual script.
Please make a effort or I will have to ignore this issue.
If you want me to add the opcode support you will have to make a minimalist sample with only the needed code(valid code) to make the script use `GEN_START` when compiled.
I don't want any actual script you just want to take the source from but a real sample for testing. If you can read the list of scripts there is no scripts for creating accounts on any website or anything.

Thanks.

**Comment by tcf38012** [comment]
> No. I assume you didn't even read the script in the `async_def.txt` file.
> 
> The samples need to be minimalist and not be a actual script. Please make a effort or I will have to ignore this issue. If you want me to add the opcode support you will have to make a minimalist sample with only the needed code(valid code) to make the script use `GEN_START` when compiled. I don't want any actual script you just want to take the source from but a real sample for testing. If you can read the list of scripts there is no scripts for creating accounts on any website or anything.
> 
> Thanks.

Like this:
```
def GEN_START():
    return (a for a, _ in getTest())
```
