### ISSUE TITLE
Unsupported opcode: POP_JUMP_FORWARD_IF_FALSE

### ISSUE THREAD

**Issue by ghost** [zrax/pycdc#336]
```
# Source Generated with Decompyle++
# File: main.pyc (Python 3.11)

Unsupported opcode: POP_JUMP_FORWARD_IF_FALSE
from PyQt5.QtCore import QThreadPool
from PyQt5.QtWidgets import QMainWindow, QApplication, QDialog, QMessageBox
from PyQt5.QtCore import Qt, pyqtSlot, QTimer, QRegExp, QThread, QDateTime, QThreadPool, QRect
from PyQt5.QtGui import QRegExpValidator
import sys
import logging
import os
import json
import re
from window import Ui_MainWindow
from setting import Ui_Form
from browser import codeMail
from thread import Worker
__version__ = '1.0'

class myWindow(QMainWindow):
Unsupported opcode: MAKE_CELL
    pass
# WARNING: Decompyle incomplete


def main():
Unsupported opcode: PUSH_EXC_INFO
    app = sys(argv.argv)
    window = QMessageBox()
    myWindow.exit(app.exec_())
    return None
# WARNING: Decompyle incomplete

# WARNING: Decompyle incomplete

```

I am getting this error. can anyone fix this problem ?

**Comment by KDot227** [comment]
I'm having the same issue right now

**Comment by ddouworld** [comment]
This is because you are trying to decompile Python 3.11 and above. This Python version adds a lot of new bytecode, and Pydoc doesn't fit this perfectly.

**Comment by waxnet** [comment]
You can try to look into the actual PYC file and try to understand what the script does from that, unless that's not what you are trying to do.

**Comment by Paim0naletka** [comment]
Add this to ASTree: `case Pyc::POP_JUMP_FORWARD_IF_TRUE_A:`
Most likely it will help you

**Comment by TheHellTower** [comment]
> ```
> # Source Generated with Decompyle++
> # File: main.pyc (Python 3.11)
> 
> Unsupported opcode: POP_JUMP_FORWARD_IF_FALSE
> from PyQt5.QtCore import QThreadPool
> from PyQt5.QtWidgets import QMainWindow, QApplication, QDialog, QMessageBox
> from PyQt5.QtCore import Qt, pyqtSlot, QTimer, QRegExp, QThread, QDateTime, QThreadPool, QRect
> from PyQt5.QtGui import QRegExpValidator
> import sys
> import logging
> import os
> import json
> import re
> from window import Ui_MainWindow
> from setting import Ui_Form
> from browser import codeMail
> from thread import Worker
> __version__ = '1.0'
> 
> class myWindow(QMainWindow):
> Unsupported opcode: MAKE_CELL
>     pass
> # WARNING: Decompyle incomplete
> 
> 
> def main():
> Unsupported opcode: PUSH_EXC_INFO
>     app = sys(argv.argv)
>     window = QMessageBox()
>     myWindow.exit(app.exec_())
>     return None
> # WARNING: Decompyle incomplete
> 
> # WARNING: Decompyle incomplete
> ```
> 
> I am getting this error. can anyone fix this problem ?

Hello, could you link a SAMPLE script that has this ? No actual script/program.

**Comment by TheHellTower** [comment]
> Add this to ASTree: `case Pyc::POP_JUMP_FORWARD_IF_FALSE_A:` Most likely it will help you

This isn't magic and each opcode need handling if you don't handle them then you will waste lines of code or get a broken output.

**Comment by nicolas2k** [comment]
Me too on ARM64 (MacOS Ventura 13.4)!

nicolas@MBP test.osx_extracted % ./pycdc test.pyc -v 311
# Source Generated with Decompyle++
# File: test.pyc (Python 3.11)

**Unsupported opcode: POP_JUMP_FORWARD_IF_FALSE**
__doc__ = "\n#\n<<< overview all sessions in kernel without exception list of know process >>>\n\n#################################################################################\n#\n# Copyright (c) 2020 <***blablabla***> license that can be\n# found in the LICENSE file.\n#\n# Python 3.4+, prerequises : pip install -r requirements.txt\n#\n\n\n"
__license__ = 'Python License 3'
__link__ = 'https://docs.python.org/3/license.html'
__author__ = 'Nicolas'
__version__ = '1.05'
__owner__ = 'nicolas2k'
__date__ = '2021-02-03 16:00:00'
__expiration__ = '2025-02-03 16:00:00'
import re
import os
import sys
import getopt
import signal
import platform
import ctypes
import socket
import time
import psutil
import yaml
from datetime import datetime
from socket import AF_INET, SOCK_STREAM, SOCK_DGRAM

def Revision():
**Error decompyling test.pyc: vector**

/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*
nicolas@MBP pyinstxtractor % python --version
Python 3.11.4

nicolas@MBP pyinstxtractor % gcc --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by nicolas2k** [comment]
### **In additional info with test code :** 
~~~Bash
import dis

def test(i):
    if i > 0: print("ok")
    else: print("ko")

dis.dis(test)
~~~


### **Compilation :** 
~~~Bash$
nicolas@MBP Compile % pyinstaller --noconfirm --onefile --console -n test.osx -F ../test.py -d noarchive -a --clean
205 INFO: PyInstaller: 5.12.0
205 INFO: Python: 3.11.4
217 INFO: Platform: macOS-13.4-arm64-arm-64bit
<...>
~~~


### **Result execution :** 
~~~Bash
nicolas@MBP Compile % ./dist/test.osx 
  3           0 RESUME                   0

  4           2 LOAD_FAST                0 (i)
              4 LOAD_CONST               1 (0)
              6 COMPARE_OP               4 (>)
             12 POP_JUMP_FORWARD_IF_FALSE    17 (to 48)
             14 LOAD_GLOBAL              1 (NULL + print)
             26 LOAD_CONST               2 ('ok')
             28 PRECALL                  1
             32 CALL                     1
             42 POP_TOP
             44 LOAD_CONST               0 (None)
             46 RETURN_VALUE

  5     >>   48 LOAD_GLOBAL              1 (NULL + print)
             60 LOAD_CONST               3 ('ko')
             62 PRECALL                  1
             66 CALL                     1
             76 POP_TOP
             78 LOAD_CONST               0 (None)
             80 RETURN_VALUE
nicolas@ Compile % 
~~~


### **Extraction library :** 
~~~Bash
nicolas@MBP pyinstxtractor % python3 pyinstxtractor.py ../../Compile/test.osx                                             
[+] Processing ../../Compile/test.osx
[+] Pyinstaller version: 2.1+
[+] Python version: 3.11
[+] Length of package: 6139361 bytes
[+] Found 159 files in CArchive
[+] Beginning extraction...please standby
[+] Possible entry point: pyiboot01_bootstrap.pyc
[+] Possible entry point: pyi_rth_inspect.pyc
[+] Possible entry point: test.pyc
[+] Found 0 files in PYZ archive
[+] Successfully extracted pyinstaller archive: ../../Compile/test.osx

You can now use a python decompiler on the pyc files within the extracted directory

nicolas@MBP pyinstxtractor % cd test.osx_extracted 
nicolas@MBP test.osx_extracted % ../../pycdc/pycdc  test.pyc
# Source Generated with Decompyle++
# File: test.pyc (Python 3.11)

import dis

def foo(x):
~~~
**_Unsupported opcode: POP_JUMP_FORWARD_IF_FALSE_**
~~~Bash
    pass
# WARNING: Decompyle incomplete

dis.dis(foo)
~~~~


### **Extraction ByteCode :** 
~~~Bash
nicolas@MBP
nicolas@MBP test.osx_extracted % ../../pycdc/pycdas test.pyc  
test.pyc (Python 3.11)
[Code]
    File Name: test.py
    Object Name: <module>
    Qualified Name: <module>
    Arg Count: 0
    Pos Only Arg Count: 0
    KW Only Arg Count: 0
    Stack Size: 3
    Flags: 0x00000000
    [Names]
        'dis'
        'test'
    [Locals+Names]
    [Constants]
        0
        None
        [Code]
            File Name: test.py
            Object Name: test
            Qualified Name: test
            Arg Count: 1
            Pos Only Arg Count: 0
            KW Only Arg Count: 0
            Stack Size: 3
            Flags: 0x00000003 (CO_OPTIMIZED | CO_NEWLOCALS)
            [Names]
                'print'
            [Locals+Names]
                'i'
            [Constants]
                None
                0
                'ok'
                'ko'
            [Disassembly]
                0       RESUME                        0
                2       LOAD_FAST                     0: i
                4       LOAD_CONST                    1: 0
                6       COMPARE_OP                    4 (>)
                12      POP_JUMP_FORWARD_IF_FALSE     17
                14      LOAD_GLOBAL                   1: NULL + print
                26      LOAD_CONST                    2: 'ok'
                28      PRECALL                       1
                32      CALL                          1
                42      POP_TOP                       
                44      LOAD_CONST                    0: None
                46      RETURN_VALUE                  
                48      LOAD_GLOBAL                   1: NULL + print
                60      LOAD_CONST                    3: 'ko'
                62      PRECALL                       1
                66      CALL                          1
                76      POP_TOP                       
                78      LOAD_CONST                    0: None
                80      RETURN_VALUE                  
    [Disassembly]
        0       RESUME                        0
        2       LOAD_CONST                    0: 0
        4       LOAD_CONST                    1: None
        6       IMPORT_NAME                   0: dis
        8       STORE_NAME                    0: dis
        10      LOAD_CONST                    2: <CODE> test
        12      MAKE_FUNCTION                 0
        14      STORE_NAME                    1: test
        16      PUSH_NULL                     
        18      LOAD_NAME                     0: dis
        20      LOAD_ATTR                     0: dis
        30      LOAD_NAME                     1: test
        32      PRECALL                       1
        36      CALL                          1
        46      POP_TOP                       
        48      LOAD_CONST                    1: None
        50      RETURN_VALUE                  

nicolas@MBP test.osx_extracted % 

~~~


I hope you have enough info ...

**Comment by zrax** [comment]
Duplicate #452
