### ISSUE TITLE
Unsupported opcode : RETURN_GENERATOR

### ISSUE THREAD

**Issue by Drago-FireFox** [zrax/pycdc#337]
hello I have a small problem in fact when I run the pycdc program to my file in ".pyc" I get this error ```Unsupported opcode: RETURN_GENERATOR```, how to solve the problem?
I have already seen the previous issues but it does not solve my problem .
 I'm on Termux under Python 3.11.2
Waiting for an answer 
Thanks in advance

**Comment by waxnet** [comment]
There is not really a fix for the problem other than waiting for pycdc to update and support the RETURN_GENERATOR opcode, meanwhile, you can try to look into the pyc file and try to understand what the script does from that.

**Comment by TheHellTower** [comment]
> hello I have a small problem in fact when I run the pycdc program to my file in ".pyc" I get this error `Unsupported opcode: RETURN_GENERATOR`, how to solve the problem? I have already seen the previous issues but it does not solve my problem . I'm on Termux under Python 3.11.2 Waiting for an answer Thanks in advance

Hello, could you link a script that has this ?

**Comment by zrax** [comment]
Duplciate #452
