### ISSUE TITLE
Unsupported opcode: KW_NAMES

### ISSUE THREAD

**Issue by Naman-Devnani** [zrax/pycdc#345]
Unsupported opcode: KW_NAMES

└─$ python3 --version
Python 3.11.2

**Comment by TheHellTower** [comment]
> Unsupported opcode: KW_NAMES
> 
> └─$ python3 --version Python 3.11.2

Hello, could you link a script that has this ?

**Comment by Naman-Devnani** [comment]
Sorry for Late Reply 

https://drive.google.com/file/d/1MFsneCN7XUv04Zx8UDZFoPMVWmTNgX75/view?usp=sharing

**Comment by TheHellTower** [comment]
> Sorry for Late Reply
> 
> https://drive.google.com/file/d/1MFsneCN7XUv04Zx8UDZFoPMVWmTNgX75/view?usp=sharing

Malwares(so this file) or any actual script/program are not accepted.
I need you to make a script that use `KW_NAMES` opcode.

**Comment by Naman-Devnani** [comment]
Yes I was converting this malware from exe to py, some of its source code is visible like first 5-6 lines but after KW_NAMES opcode error is coming.

**Comment by TheHellTower** [comment]
> Yes I was converting this malware from exe to py, some of its source code is visible like first 5-6 lines but after KW_NAMES opcode error is coming.

Well, I will be more clear, you have to send a script that actually produce the `KW_NAMES` opcode when compiled. I'm not working with actual scripts/programs and even less with malwares.

@Remi-Avec-Un-I can you make a script with this opcode or are you dead ?

**Comment by stfzy** [comment]
[wenda11.zip](https://github.com/zrax/pycdc/files/11645520/wenda11.zip)

**Comment by TheHellTower** [comment]
> Reference in new
`I'm not working with actual scripts/programs and even less with malwares.`

Example of what we call a sample, watch the scripts: https://github.com/zrax/pycdc/tree/master/tests/input

**Comment by asadilo** [comment]
I have the same problem

**Comment by asadilo** [comment]
Does anyone have a complete solution for this

**Comment by TheHellTower** [comment]
> Does anyone have a complete solution for this

Hello,

See https://github.com/zrax/pycdc/pull/365 it contain a solution even thought it might not be perfect for the moment.

I'm personally waiting to get the ability to get a new setup and a personal place to continue trying to help this project for some private reasons sorry.

Best Regards,
TheHellTower.

**Comment by asadilo** [comment]
> > Buning uchun to'liq yechim bormi
> 
> Salom,
> 
> [№ 365-ga](https://github.com/zrax/pycdc/pull/365) qarang , u hozircha mukammal bo'lishi mumkin deb o'ylagan yechimni o'z ichiga oladi.
> 
> Kechirasiz, sabablarga ko'ra foydalanishga yordam berishda davom etaman.
> 
> Hurmat bilan, TheHellTower.

Can we contact you by telegram?
this is my telegram profile:@Asadillooooo7
or leave your own

**Comment by TheHellTower** [comment]
> > > Buning uchun to'liq yechim bormi
> > 
> > 
> > Salom,
> > [№ 365-ga](https://github.com/zrax/pycdc/pull/365) qarang , u hozircha mukammal bo'lishi mumkin deb o'ylagan yechimni o'z ichiga oladi.
> > Kechirasiz, sabablarga ko'ra foydalanishga yordam berishda davom etaman.
> > Hurmat bilan, TheHellTower.
> 
> Can we contact you by telegram? this is my telegram profile:@Asadillooooo7 or leave your personal profile

Telegram: https://t.me/THeHellTower

**Comment by zrax** [comment]
Resolved with #365
