### ISSUE TITLE
Unsupported opcode: RERAISE,JUMP_BACKWARD,KW_NAMES,POP_JUMP_FORWARD_IF_FALSE

### ISSUE THREAD

**Issue by lixsg** [zrax/pycdc#358]

**Comment by TheHellTower** [comment]
> _No description provided._

Hello, 

Could you if possible send scripts samples(not compiled) using the not supported yet opcodes and specify the python version ?

Don't send any automation script or stuff like this it has to be a very simple script that will use the wanted and targeted opcodes.

Examples: https://github.com/zrax/pycdc/tree/master/tests/input

Regards.

**Comment by lixsg** [comment]
python3.9 unsupport 
```
try:
   open('1.txt')
catch Exception as e:
   print(e)

**Comment by lixsg** [comment]
python 3.9
```
def test():
    try:
        open('1.txt')
    except Exception as e:
        print(e)

**Comment by lixsg** [comment]
python3.9.7 win11
```
try:
    raise Exception("I am an exception")
except Exception as e:
    print(e)
finally:
    print("The finally code")

**Comment by TheHellTower** [comment]
> python3.9.7 win11
> 
> ```
> try:
>     raise Exception("I am an exception")
> except Exception as e:
>     print(e)
> finally:
>     print("The finally code")
> ```
> 
> ......

Hey, I can't see the following OPCodes in your title:
- `JUMP_BACKWARD`
- `KW_NAMES`
- `JUMP_BACKWARD`
- `POP_JUMP_FORWARD_IF_FALSE `

Tell me if you can give a sample otherwise I will only be able to verify `RERAISE` for the moment !

**Comment by TiZCrocodile** [comment]
> > python3.9.7 win11
> > ```
> > try:
> >     raise Exception("I am an exception")
> > except Exception as e:
> >     print(e)
> > finally:
> >     print("The finally code")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ......
> 
> Hey, I can't see the following OPCodes in your title:
> 
> * `JUMP_BACKWARD`
> * `KW_NAMES`
> * `JUMP_BACKWARD`
> * `POP_JUMP_FORWARD_IF_FALSE `
> 
> Tell me if you can give a sample otherwise I will only be able to verify `RERAISE` for the moment !

here is a sample code creating the following unsupported opcodes:
* `JUMP_BACKWARD`
* `POP_JUMP_FORWARD_IF_FALSE`
* `CHECK_EXC_MATCH`
* `RERAISE`
* `PUSH_EXC_INFO`
* `COPY`
* `KW_NAMES`

```
def foo(x):
	print(x)

foo(x=5)
l = [int(num.strip()) for num in '123 \n456 '.split('\n')]
a = 10
if a == 10:
	print('a is 10')
else:
	print('a is not 10')
try:
    raise Exception("I am an exception")
except Exception as e:
    print(e)
finally:
    print("The finally code")
```

**Comment by TheHellTower** [comment]
> > > python3.9.7 win11
> > > ```
> > > try:
> > >     raise Exception("I am an exception")
> > > except Exception as e:
> > >     print(e)
> > > finally:
> > >     print("The finally code")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ......
> > 
> > 
> > Hey, I can't see the following OPCodes in your title:
> > 
> > * `JUMP_BACKWARD`
> > * `KW_NAMES`
> > * `JUMP_BACKWARD`
> > * `POP_JUMP_FORWARD_IF_FALSE `
> > 
> > Tell me if you can give a sample otherwise I will only be able to verify `RERAISE` for the moment !
> 
> python 3.11.4, win10, pyinstaller==5.13.0 (latest, 29 june 2023) here is a sample code creating the following unsupported opcodes:
> 
> * `JUMP_BACKWARD`
> * `POP_JUMP_FORWARD_IF_FALSE`
> * `CHECK_EXC_MATCH`
> * `RERAISE`
> * `PUSH_EXC_INFO`
> * `COPY`
> * `KW_NAMES`
> 
> ```
> def foo(x):
>     print(x)
> 
> foo(x=5)
> l = [int(num.strip()) for num in '123 \n456 '.split('\n')]
> a = 10
> if a == 10:
>     print('a is 10')
> else:
>     print('a is not 10')
> try:
>     raise Exception("I am an exception")
> except Exception as e:
>     print(e)
> finally:
>     print("The finally code")
> ```
> 
> here is the disassembly using pycdas:
> ......

Hey, 

Thanks for your help and the disassembly is useless on my side if you are already sure of which OPCodes are generated !

The problem is that I would need a sample per OPCode(when possible because in some situations it require more OPCodes) because I personally try to fix them without having a lot of info on pycdc and python runtime itself as I don't have much time to check them more deeply(they are pretty complexe), so if you can separate them it would be very nice ! Otherwise I will see what I can do !
I also can't promise to solve all of them but I will try my best when I will get some time !

P.S: My contact in case you need a faster answer: thehelltower@tuta.io

Best Regards,
TheHellTower.

**Comment by TiZCrocodile** [comment]
@TheHellTower 
Here is sample codes for the unsupported opcodes, with a little explanation of what I understood:
For the following opcodes:

1. `JUMP_BACKWARD`
2. `KW_NAMES`
3. `POP_JUMP_FORWARD_IF_FALSE`
4. `PUSH_EXC_INFO`
5. `COPY`
6. `RERAISE`
7. `CHECK_EXC_MATCH`
---
* `JUMP_BACKWARD`
```
l = [char for char in 'hello']
```
---
probably generated because the names of the arguments:
* `KW_NAMES`
```
def foo(x):
    print(x)
foo(x='hello')
```
---
this one I think is just `POP_JUMP_IF_FALSE`, so just adding it to the `switch(opcode)` in the code probably will fix it
* `POP_JUMP_FORWARD_IF_FALSE`
```
if 1 == 0:
    print('TRUE')
print('FALSE (so jumping forward)')
```
---
* `PUSH_EXC_INFO`
* `COPY`
* `RERAISE`
```
try:
    pass
except:
    pass
```
---
this one is almost the same as previous, just that it needs to check if the except is one of the exception types specified -
if not, it will do `POP_JUMP_FORWARD_IF_FALSE`
* `CHECK_EXC_MATCH`
```
try:
    pass
except Exception:
    pass
```

**Comment by TheHellTower** [comment]
> ```
> l = [char for char in 'hello']
> ```

Thank you I will check this out in the week and see if I can get some fixed !

**Comment by TheHellTower** [comment]
> I met the same question. Actually, pycdc is the only project can decompile the python3.11. I do hope you can solve the question.

Yeah sorry for the moments I have things to do to survive haha but when I will have free time I will look at it I taken this issue in notes since it actually give codes to look at to fix the issues(not like most of the issues sadly)

**Comment by Denzy7** [comment]
Before no-op for `KW_NAMES` in `switch (opcode)`
`from github import Github
from cachetools import TTLCache
access_token = 'redacted'
g = Github(access_token)`

After
`from github import Github
from cachetools import TTLCache
access_token = 'redacted'
g = Github(access_token)
cache = None(TTLCache, 100)
repo = g.get_repo('redacted/redacted')
file_path = 'redacted'`

I don't have actual source for obvious reasons

**Comment by Scenial** [comment]
ummm did jump_backward fixed yet?

**Comment by TiZCrocodile** [comment]
> ummm did jump_backward fixed yet?

dont think so

**Comment by Scenial** [comment]
> > ummm did jump_backward fixed yet?
> 
> dont think so

any idea to make it work?

**Comment by TiZCrocodile** [comment]
> > > ummm did jump_backward fixed yet?
> > 
> > 
> > dont think so
> 
> any idea to make it work?

As I remember it was very similar to JUMP_ABSOLUTE, so probably they changed JUMP_ABSOLUTE to JUMP_BACKWARD i guess, so i think the implementation should be similar to JUMP_ABSOLUTE

**Comment by TiZCrocodile** [comment]
> > > > > ummm did jump_backward fixed yet?
> > > > 
> > > > 
> > > > dont think so
> > > 
> > > 
> > > any idea to make it work?
> > 
> > 
> > As I remember it was very similar to JUMP_ABSOLUTE, so probably they changed JUMP_ABSOLUTE to JUMP_BACKWARD i guess, so i think the implementation should be similar to JUMP_ABSOLUTE
> 
> cool, but i dont dont really know how to fix it by myself tho, can u like give me an example

alright so when i'll get to my home i could help you, in 3-4 hours i could help you if you want or maybe tomorrow

**Comment by Scenial** [comment]
> > > > > > ummm did jump_backward fixed yet?
> > > > > 
> > > > > 
> > > > > dont think so
> > > > 
> > > > 
> > > > any idea to make it work?
> > > 
> > > 
> > > As I remember it was very similar to JUMP_ABSOLUTE, so probably they changed JUMP_ABSOLUTE to JUMP_BACKWARD i guess, so i think the implementation should be similar to JUMP_ABSOLUTE
> > 
> > 
> > cool, but i dont dont really know how to fix it by myself tho, can u like give me an example
> 
> alright so when i'll get to my home i could help you, in 3-4 hours i could help you if you want or maybe tomorrow

add my discord naity69

**Comment by TiZCrocodile** [comment]
> naity69

it doesn't exist

**Comment by Scenial** [comment]
> > naity69
> 
> it doesn't exist

discord down, any way to contact you?

**Comment by TiZCrocodile** [comment]
> > > naity69
> > 
> > 
> > it doesn't exist
> 
> discord down, any way to contact you?

oh, so i'll try to create a server then we will join wait

**Comment by TiZCrocodile** [comment]
> > > naity69
> > 
> > 
> > it doesn't exist
> 
> discord down, any way to contact you?

I think it was a bug or something but i sent you the friend request now, closed and opened discord and it worked

**Comment by Scenial** [comment]
> > > > naity69
> > > 
> > > 
> > > it doesn't exist
> > 
> > 
> > discord down, any way to contact you?
> 
> I think it was a bug or something but i sent you the friend request now, closed and opened discord and it worked

check dms

**Comment by b2nzy** [comment]
added support for PUSH_EXC_INFO?

**Comment by TiZCrocodile** [comment]
> added support for PUSH_EXC_INFO?

still not, im on it here and there on my fork repo, its related to exceptions which is a little hard to decompile and understand for me at least

**Comment by b2nzy** [comment]
> > added support for PUSH_EXC_INFO?
> 
> still not, im on it here and there on my fork repo, its related to exceptions which is a little hard to decompile and understand for me at least

we hope you will add support for all opcodes

**Comment by TiZCrocodile** [comment]
> > > added support for PUSH_EXC_INFO?
> > 
> > 
> > still not, im on it here and there on my fork repo, its related to exceptions which is a little hard to decompile and understand for me at least
> 
> we hope you will add support for all opcodes

wow, thats actually gives motivation man, I guess I need to do it damn

**Comment by TheHellTower** [comment]
> > > added support for PUSH_EXC_INFO?
> > 
> > 
> > still not, im on it here and there on my fork repo, its related to exceptions which is a little hard to decompile and understand for me at least
> 
> we hope you will add support for all opcodes

To be honest you can't expect someone to add support for all OpCodes, as many users already use pycdc for pretty bad purposes (`getting program code to copy/paste & resell`)...

But above all, if he had to add all the missing OpCodes (for all versions, for example) it would be a lot of work.
Maybe you're only talking about the ones in the issue, I'm not sure.

**Comment by TiZCrocodile** [comment]
> > > > added support for PUSH_EXC_INFO?
> > > 
> > > 
> > > still not, im on it here and there on my fork repo, its related to exceptions which is a little hard to decompile and understand for me at least
> > 
> > 
> > we hope you will add support for all opcodes
> 
> To be honest you can't expect someone to add support for all OpCodes, as many users already use pycdc for pretty bad purposes (`getting program code to copy/paste & resell`)...
> 
> But above all, if he had to add all the missing OpCodes (for all versions, for example) it would be a lot of work. Maybe you're only talking about the ones in the issue, I'm not sure.

i actually want to add support for all opcodes, i dont think the rest of the opcodes is that hard, i think the exceptions is one of the hardest to do, but i just want to first do the exceptions and then do the rest, like an OCD, but anyway im not on it 24/7, im a bit lazy, maybe some week i will go all in on this and finish this already.

**Comment by b2nzy** [comment]
> > > > added support for PUSH_EXC_INFO?
> > > 
> > > 
> > > still not, im on it here and there on my fork repo, its related to exceptions which is a little hard to decompile and understand for me at least
> > 
> > 
> > we hope you will add support for all opcodes
> 
> To be honest you can't expect someone to add support for all OpCodes, as many users already use pycdc for pretty bad purposes (`getting program code to copy/paste & resell`)...
> 
> But above all, if he had to add all the missing OpCodes (for all versions, for example) it would be a lot of work. Maybe you're only talking about the ones in the issue, I'm not sure.

Well, in most cases I use pycdc to decompile the virus and then remove the webhook if it's there

**Comment by TheHellTower** [comment]
> > > > > added support for PUSH_EXC_INFO?
> > > > 
> > > > 
> > > > still not, im on it here and there on my fork repo, its related to exceptions which is a little hard to decompile and understand for me at least
> > > 
> > > 
> > > we hope you will add support for all opcodes
> > 
> > 
> > To be honest you can't expect someone to add support for all OpCodes, as many users already use pycdc for pretty bad purposes (`getting program code to copy/paste & resell`)...
> > But above all, if he had to add all the missing OpCodes (for all versions, for example) it would be a lot of work. Maybe you're only talking about the ones in the issue, I'm not sure.
> 
> i actually want to add support for all opcodes, i dont think the rest of the opcodes is that hard, i think the exceptions is one of the hardest to do, but i just want to first do the exceptions and then do the rest, like an OCD, but anyway im not on it 24/7, im a bit lazy, maybe some week i will go all in on this and finish this already.

I kinda wanted to do it too but got some things to solve IRL and still in things.. Also I don't understand pycdc enough to implement all OpCodes anyway, hopefully you are not forcing yourself to do this.

**Comment by TheHellTower** [comment]
> > > > > added support for PUSH_EXC_INFO?
> > > > 
> > > > 
> > > > still not, im on it here and there on my fork repo, its related to exceptions which is a little hard to decompile and understand for me at least
> > > 
> > > 
> > > we hope you will add support for all opcodes
> > 
> > 
> > To be honest you can't expect someone to add support for all OpCodes, as many users already use pycdc for pretty bad purposes (`getting program code to copy/paste & resell`)...
> > But above all, if he had to add all the missing OpCodes (for all versions, for example) it would be a lot of work. Maybe you're only talking about the ones in the issue, I'm not sure.
> 
> Well, in most cases I use pycdc to decompile the virus and then remove the webhook if it's there

If you want to remove a webhook it's "easier" than you think, most of the time you can use an HTTP Debugger and the software doesn't "care".. So you can get the webhook from here and then send a `DELETE` request to it so it gets deleted.

**Comment by b2nzy** [comment]
> If you want to remove a webhook it's "easier" than you think, most of the time you can use an HTTP Debugger and the software doesn't "care".. So you can get the webhook from here and then send a `DELETE` request to it so it gets deleted.

Thanks for the tip. I'll keep that in mind.

**Comment by TheHellTower** [comment]
> > If you want to remove a webhook it's "easier" than you think, most of the time you can use an HTTP Debugger and the software doesn't "care".. So you can get the webhook from here and then send a `DELETE` request to it so it gets deleted.
> 
> Thanks for the tip. I'll keep that in mind.

No problem, the following tools can be an option if you don't want to waste your time on decompilation:

- [HTTP Debugger Pro](https://www.httpdebugger.com)
- [Fiddler](https://www.telerik.com/fiddler)
- [Wireshark](https://www.wireshark.org)

**Comment by TheHellTower** [comment]
Hello @TiZCrocodile,

Do you have any way to be contacted outside of GitHub ?(`Discord, E-Mail, Telegram, other ?`)

Taking into account https://github.com/zrax/pycdc/issues/358#issuecomment-1747290224 and the fact you looks kinda comfortable with the project I would like to ask some questions and learn some things if you don't mind so I could help better this project and maybe split the work with you to makes it faster and "`easier`".

<details>
    <summary>
        Contact ? Click Here.
    </summary>

Discord: TheHellTower
Telegram: [TheHellTower](https://t.me/TheHellTower)
E-Mail: [thehelltower@tuta.io](mailto:thehelltower@tuta.io)
</details>

Best Regards,
TheHellTower.

**Comment by TiZCrocodile** [comment]
> Hello @TiZCrocodile,
> 
> Do you have any way to be contacted outside of GitHub ?(`Discord, E-Mail, Telegram, other ?`)
> 
> Taking into account [#358 (comment)](https://github.com/zrax/pycdc/issues/358#issuecomment-1747290224) and the fact you looks kinda comfortable with the project I would like to ask some questions and learn some things if you don't mind so I could help better this project and maybe split the work with you to makes it faster and "`easier`".
> 
> Contact ? Click Here.
> Best Regards, TheHellTower.

sure, on discord its fine, im sending you friend request

**Comment by zrax** [comment]
Duplicate #450 #452
