### ISSUE TITLE
Incorrect handling of operand naming in versions prior to 3.11

### ISSUE THREAD

**Issue by PolyFlower** [zrax/pycdc#374]
Issue:
* pycdas generates incorrect names for operands in versions lower then 3.11, since there is no explicit check for module version.

https://github.com/zrax/pycdc/blob/bb54b27cd10ecd3b06a7c4d4237a19c3af21b42c/bytecode.cpp#L395-L404

Proposed Solution:
* Inspect the logic responsible for formatting operand names and adjust it to ensure consistent and accurate formatting for Python 3.11 and below. Consider a basic check like:
```c++
mod->verCompare(3, 11)
```

**Comment by zrax** [comment]
Fixed by #375.  Thanks
