### ISSUE TITLE
Unsupported opcode: 

### ISSUE THREAD

**Issue by JZZLQ** [zrax/pycdc#377]
Unsupported opcode: POP_JUMP_FORWARD_IF_FALSE
Unsupported opcode: POP_JUMP_FORWARD_IF_FALSE
Unsupported opcode: JUMP_BACKWARD
Unsupported opcode: KW_NAMES
Error decompyling 1.pyc: invalid vector subscript

script download url:
[https://tria.ge/samples/230823-gbl4ssaa57/sample.zip](url)

**Comment by SleepingPig35** [comment]
Fixed in [this PR?](https://github.com/zrax/pycdc/commit/da859f5a2bc7636ca5bd8aa29707a619149b620a)
Please use the latest version of pycdc!

**Comment by Hun7er999** [comment]
> Fixed in [this PR?](https://github.com/zrax/pycdc/commit/da859f5a2bc7636ca5bd8aa29707a619149b620a) Please use the latest version of pycdc!

not JUMP_BACKWARDS

**Comment by fluffysnaff** [comment]
Are you gonna add this soon?

**Comment by fluffysnaff** [comment]
how much money for you to add this

**Comment by greenozon** [comment]
>script download url:
>[https://tria.ge/samples/230823-gbl4ssaa57/sample.zip](https://github.com/zrax/pycdc/issues/url)

not available, please reup

**Comment by izhgtumekhanik** [comment]
> how much money for you to add this

1 000 000 $

**Comment by zzq517** [comment]
The download address has expired. Can you please provide it again? Thank you very much

**Comment by zrax** [comment]
Duplicate #452
