### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by b2nzy** [zrax/pycdc#387]
python 3.11 Segmentation fault

root@ruvds-sc7w2:~# ./pycdc edit.pyc
# Source Generated with Decompyle++
# File: edit.pyc (Python 3.11)

Segmentation fault

**Comment by b2nzy** [comment]
[https://cdn.discordapp.com/attachments/1127852118846480484/1158422829700763648/edit.pyc?ex=651c30d5&is=651adf55&hm=a5de1f0f1554d556585134c46ef5363bc1a3b6d1069b9c752536d06475e71fb1&](url)

pyc file

**Comment by greenozon** [comment]
@b2nzy 
"This content is no longer available."
