### ISSUE TITLE
Unsupported opcode: POP_JUMP_BACKWARD_IF_FALSE

### ISSUE THREAD

**Issue by Rylazius** [zrax/pycdc#388]
pycdc from : https://github.com/extremecoders-re/decompyle-builds/releases/tag/build-28-Aug-2023-d62c8ad

**Comment by TheHellTower** [comment]
> pycdc from : https://github.com/extremecoders-re/decompyle-builds/releases/tag/build-28-Aug-2023-d62c8ad

Hello, could you provide a sample script ?

**Comment by zrax** [comment]
Duplicate #452
