### ISSUE TITLE
Unknown opcode: BEFORE_WITH

### ISSUE THREAD

**Issue by matthewransley** [zrax/pycdc#394]
In 3.11, BEFORE_WITH opcode was added, see: https://docs.python.org/3/library/dis.html#opcode-BEFORE_WITH, and it appears as though this project doesnt support it just yet

**Comment by greenozon** [comment]
there are dozens of other non-supported yet opcodes...

Please attach your .pyc

**Comment by Imma-P** [comment]
> there are dozens of other non-supported yet opcodes...
> 
> Please attach your .pyc

Hello, I need help for this opcode too. For the pyc file please add me on tg -> imma_pro

**Comment by charlyzard** [comment]
[main.zip](https://github.com/zrax/pycdc/files/13533952/main.zip)
Attaching a sample pyc file with this opcode.

**Comment by zrax** [comment]
Duplicate #452
