### ISSUE TITLE
Unsupported opcode: MAKE_CELL and Vector Error

### ISSUE THREAD

**Issue by gaplan** [zrax/pycdc#401]
Unsupported opcode: MAKE_CELL
    pass
# WARNING: Decompyle incomplete

Error decompyling /Users/knicks/Desktop/stream.pyc: vector

**Comment by gaplan** [comment]
pycdc-master-2 % ./pycdc  /Users/knicks/Desktop/stream.pyc 
# Source Generated with Decompyle++
# File: stream.pyc  (Python 3.12)

import json
import sys
import random
import time
from time import sleep as sleep
import string
import subprocess
from datetime import datetime
import pytz
from threading import Thread, Barrier
import requests

def add_log(error_message):
Error decompyling /Users/knicks/Desktop/stream.pyc: vector

**Comment by greenozon** [comment]
please attach your .pyc file

**Comment by charlyzard** [comment]
[bf.zip](https://github.com/zrax/pycdc/files/13534020/bf.zip)
Attaching sample file with "Unsupported opcode: MAKE_CELL"

**Comment by zrax** [comment]
Duplicate #452
