### ISSUE TITLE
Unsupported opcode: POP_JUMP_IF_NONE, BEFORE_WITH

### ISSUE THREAD

**Issue by RandomStrangerOnTheInternet** [zrax/pycdc#402]
When decompiling a `Python 3.12` pyc file I receive the following errors, I would love to be able to assist with troubleshooting although I do not have access to the original source code anymore.

**Comment by RandomStrangerOnTheInternet** [comment]
Would there be a possibility to 'ignore' these opcodes and to decompile the rest of the code anyways?

**Comment by greenozon** [comment]
Please attach your .pyc file

**Comment by RandomStrangerOnTheInternet** [comment]
[shark.zip](https://github.com/zrax/pycdc/files/13403500/shark.zip)

**Comment by greenozon** [comment]
Here is an educated try to decompile your pyc
Please note that it has got much more unsupported opcodes (not just 2 mentioned in the issue name...)
but I guess it's enough to understand main logic...

https://www.sendspace.com/file/7bipte
del
https://www.sendspace.com/delete/7bipte/db967d613904993ae03f228bc2e77a2b

**Comment by RandomStrangerOnTheInternet** [comment]
Awesome, thanks a lot! That should be good enough for me to recover what was left of it <3
