### ISSUE TITLE
311 vector range issue 

### ISSUE THREAD

**Issue by rameshkabade** [zrax/pycdc#403]
def instrument_calc(symbolss):
Error decompyling /mnt/c/Users/A1/Desktop/Hari base/base (1).exe_extracted/base.pyc: vector::_M_range_check: __n (which is 8) >= this->size() (which is 6)

**Comment by greenozon** [comment]
Please attach your .pyc file

**Comment by rameshkabade** [comment]
attached pyc for your reference

Thanks
Ramesh

**Comment by greenozon** [comment]
the attachment is not visible in this issue thread
please try again...

**Comment by rameshkabade** [comment]
re-attached
[base.zip](https://github.com/zrax/pycdc/files/13406304/base.zip)

**Comment by greenozon** [comment]
Here is my humble try to recover it...
https://www.sendspace.com/file/ijswps
del
https://www.sendspace.com/delete/ijswps/61cefe8ab3e01f7214a65022d4f1a9bb

**Comment by rameshkabade** [comment]
@greenozon please help me to fix

**Comment by zrax** [comment]
Should be fixed with #462
