### ISSUE TITLE
Error decompyling file.pyc: vector::_M_range_check: __n (which is 10) >= this->size() (which is 7)

### ISSUE THREAD

**Issue by GDMgmer3992** [zrax/pycdc#404]
Python 3.11.6
https://github.com/GDMgmer3992/help/blob/main/file.pyc
pycdc.exe file.pyc

from re import search
from secrets import token_hex
import requests
import threading
import os
from os import system
from time import sleep
from requests import Session
from httpx import get
from colorama import Fore
from time import sleep
from requests import get
from subprocess import check_output
from os import system
from httpx import Client
from pystyle import Add, Center, Anime, Colors, Colorate, Write, System
from datetime import datetime
os.system('cls & mode 85,14 & title DisconnectZc#2000')

def now():
    now = datetime.now()
    nownow = now.strftime('%H:%M:%S')
    return nownow

format_one = 0
format_two = 0
format_tre = 0
loop_types = 1

def receive_color():
Error decompyling file.pyc: vector::_M_range_check: __n (which is 10) >= this->size() (which is 7)

**Comment by GDMgmer3992** [comment]
also anyone knows how to decrypt marshal?

**Comment by greenozon** [comment]
Here is improved result:

```
# File: file-issue404.pyc (Python 3.11)

from re import search
from secrets import token_hex
import requests
import threading
import os
from os import system
from time import sleep
from requests import Session
from httpx import get
from colorama import Fore
from time import sleep
from requests import get
from subprocess import check_output
from os import system
from httpx import Client
from pystyle import Add, Center, Anime, Colors, Colorate, Write, System
from datetime import datetime
os.system('cls & mode 85,14 & title DisconnectZc#2000')

def now():
    now = datetime.now()
    nownow = now.strftime('%H:%M:%S')
    return nownow

format_one = 0
format_two = 0
format_tre = 0
loop_types = 1

def receive_color():
Warning: block stack is not empty!
    global loop_types
    for types1, types2, types3, number in zip([
        1,
        0], [
        0,
        1], [
        '+',
        '-'], [
        255,
        0]):
        if loop_types == types1:
            if format_one != number:
                exec(f'''format_one {types3}= 15''', globals())
            if format_one == number and format_two != number:
                exec(f'''format_two {types3}= 15''', globals())
            if format_two == number and format_tre != number:
                exec(f'''format_tre {types3}= 15''', globals())
            if format_tre == number:
                loop_types = types2
        return f'''\x1b[38;2;{format_one};{format_two};{format_tre}m'''

os.system('cls & mode 85,14 & title DisconnectZc#2000')

def sms_pam():
Unsupported opcode: MAKE_CELL
    pass
# WARNING: Decompyle incomplete


class AOC:

    def start():
        sms_pam()


if __name__ == '__main__':
    system('cls || clear')
    AOC.start()
    return None

```


I"m not quite sure how to properly add the new opcode
`MAKE_CELL`

![image](https://github.com/zrax/pycdc/assets/765343/ffbfa8bb-b962-48b1-b3c7-1cd8a15715a8)

**Comment by greenozon** [comment]
Wow!  the disassemble file  is almost 1 Megabyte...
it means the above output is very small piece of the full decompilation...

**Comment by GDMgmer3992** [comment]
Can You Send The Whole Src File Here

**Comment by GDMgmer3992** [comment]
@greenozon

**Comment by magicwenli** [comment]
MAKE_CELL is feature release with python 3.11.
https://docs.python.org/3/whatsnew/3.11.html#new-opcodes

Need some work with ASTNode and ASTree to support it.

**Comment by rev1995** [comment]
@greenozon  can you please help on below error:

Error decompyling /home/ubuntu/pycdc/main.pyc: vector::_M_range_check: __n (which is 124) >= this->size() (which is 63)

pyc file: https://github.com/redianmarku/Telegram-Member-Adder/blob/main/main.pyc

**Comment by shoaibhassan0** [comment]
> Here is improved result:
> 
> ```
> # File: file-issue404.pyc (Python 3.11)
> 
> from re import search
> from secrets import token_hex
> import requests
> import threading
> import os
> from os import system
> from time import sleep
> from requests import Session
> from httpx import get
> from colorama import Fore
> from time import sleep
> from requests import get
> from subprocess import check_output
> from os import system
> from httpx import Client
> from pystyle import Add, Center, Anime, Colors, Colorate, Write, System
> from datetime import datetime
> os.system('cls & mode 85,14 & title DisconnectZc#2000')
> 
> def now():
>     now = datetime.now()
>     nownow = now.strftime('%H:%M:%S')
>     return nownow
> 
> format_one = 0
> format_two = 0
> format_tre = 0
> loop_types = 1
> 
> def receive_color():
> Warning: block stack is not empty!
>     global loop_types
>     for types1, types2, types3, number in zip([
>         1,
>         0], [
>         0,
>         1], [
>         '+',
>         '-'], [
>         255,
>         0]):
>         if loop_types == types1:
>             if format_one != number:
>                 exec(f'''format_one {types3}= 15''', globals())
>             if format_one == number and format_two != number:
>                 exec(f'''format_two {types3}= 15''', globals())
>             if format_two == number and format_tre != number:
>                 exec(f'''format_tre {types3}= 15''', globals())
>             if format_tre == number:
>                 loop_types = types2
>         return f'''\x1b[38;2;{format_one};{format_two};{format_tre}m'''
> 
> os.system('cls & mode 85,14 & title DisconnectZc#2000')
> 
> def sms_pam():
> Unsupported opcode: MAKE_CELL
>     pass
> # WARNING: Decompyle incomplete
> 
> 
> class AOC:
> 
>     def start():
>         sms_pam()
> 
> 
> if __name__ == '__main__':
>     system('cls || clear')
>     AOC.start()
>     return None
> ```
> 
> I"m not quite sure how to properly add the new opcode `MAKE_CELL`
> 
> ![image](https://private-user-images.githubusercontent.com/765343/284327778-ffbfa8bb-b962-48b1-b3c7-1cd8a15715a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzczNzYsIm5iZiI6MTcwNzEzNzA3NiwicGF0aCI6Ii83NjUzNDMvMjg0MzI3Nzc4LWZmYmZhOGJiLWI5NjItNDhiMS1iM2M3LTFjZDhhMTU3MTVhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxMjQ0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODNlZTc4NzcxOGQ1MjZiYzRlNWVlMjI2ZmVjZmQ3NWVhZTg2Y2YxNjczMjkzNTkzYzg1ZjY2NWI4N2I5MGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wGidIC43-B4h3ZfdAMrZNfUSeTevLEgmluCbNlwFxkc)

Can you help me how to add new opcode like MAKE_CEL i have the same issue

**Comment by OBBUYU** [comment]
@greenozon I know you can solve it. What method was used? If you could tell me, I would greatly appreciate it
