### ISSUE TITLE
how to deal this problem

### ISSUE THREAD

**Issue by l1053727938** [zrax/pycdc#407]
# Source Generated with Decompyle++
# File: cli.pyc (Python 3.11)

import json
import logging
import os
import sys
import tempfile
from argparse import ArgumentParser
from typing import Optional
from urllib.parse import urlparse
import requests
from katiska.bom.utils import print_filetree
from requests.exceptions import RequestException
from __version__ import __useragent__, __version__
from config import MAX_NESTED_ARCHIVES_EXTRACT, ScannerConfig
from findlib import ROAnalyzer
from logutils import get_logger, setup_logger_handlers
from remote import get_file
from resultbundle import create_results_bdio_json, create_results_bdio_protobuf_zip, create_results_json_cli, serialize_bundle_to_fd
from sca.signatures import JSONSetEncoder
from statuscodes import failed_to_put_result, unable_to_download_file
from utils import sha1file
logger = get_logger(__package__)
REMOTE_SCHEMES = ('http', 'https', 'docker-registry-http', 'docker-registry-https', 's3', 'ftp')

def get_default_log_format():
    if sys.stdout.isatty():
        return 'colored'

def _init_arguments_parser():
Error decompyling cli.pyc: vector::_M_range_check: __n (which is 10) >= this->size() (which is 7)

**Comment by rev1995** [comment]
can anyone please help on below error:

Error decompyling /home/ubuntu/pycdc/main.pyc: vector::_M_range_check: __n (which is 124) >= this->size() (which is 63)

pyc file: https://github.com/redianmarku/Telegram-Member-Adder/blob/main/main.pyc

**Comment by zrax** [comment]
Should be fixed with #462
