### ISSUE TITLE
Unsupported opcode: PUSH_EXC_INFO

### ISSUE THREAD

**Issue by ThePrainsLive** [zrax/pycdc#409]
# Source Generated with Decompyle++
# File: a.pyc (Python 3.11)

Unsupported opcode: PUSH_EXC_INFO
import time
import selenium
import requests
import random
import json
import string
import os
import re
import locale
import unidecode
import base64
# WARNING: Decompyle incomplete

pyc:
https://drive.google.com/file/d/1m_5XpBImkNeB5oTZ_uc2bQLe4Xwf4qu4/view?usp=sharing

**Comment by ThePrainsLive** [comment]
[a.zip](https://github.com/zrax/pycdc/files/13602112/a.zip)

Is there anyone who can help?

**Comment by greenozon** [comment]
Sorry, but this issue is more complicated..
Need more time to understand the flow,
for the moment it shows this exception and crashing

![image](https://github.com/zrax/pycdc/assets/765343/c44170f7-077b-4a9a-9324-1227b920569a)

**Comment by ThePrainsLive** [comment]
Thank you. Is it possible that the pyc file is corrupt?
Is it related to Python version? I can send you the orj exe

**Comment by greenozon** [comment]
no, I guess your pyc is valid, but the pycdc tool can't walk properly for all the nodes/opcodes inside....
what do you mean under orj exe
pyc is generated out of .py file, ins't it?

**Comment by ThePrainsLive** [comment]
I converted exe to pyc file with Pydumpck. Is there any problem caused by this? I wanted to ask him. As far as I understand pydc does not fully support 3.11
[exe.zip](https://github.com/zrax/pycdc/files/13628336/exe.zip)

**Comment by greenozon** [comment]
>As far as I understand pydc does not fully support 3.11

yes, there are many new (or changed) python opcodes not supported for 3.11/3.12 versions..

**Comment by ThePrainsLive** [comment]
> > Anladığım kadarıyla pydc 3.11'i tam olarak desteklemiyor
> 
> evet, 3.11/3.12 sürümleri için desteklenmeyen birçok yeni (veya değiştirilmiş) python işlem kodu vardır.

Thank you for the information. I want to buy you coffee. I didn't see your link in your profile.

**Comment by greenozon** [comment]
Thanks mate
I"ve added the link :)

**Comment by ThePrainsLive** [comment]
> Thanks mate I"ve added the link :)
Yes I saw :)

**Comment by ThePrainsLive** [comment]
@greenozon 
I'm trying it in another file, but there are different problems again. What could I be doing wrong?
pyc python3.10
[main.zip](https://github.com/zrax/pycdc/files/13693724/main.zip)

**Comment by greenozon** [comment]
try this of course it's not ideal, sorry
[main.cdc1.txt](https://github.com/zrax/pycdc/files/13697466/main.cdc1.txt)

**Comment by ThePrainsLive** [comment]
> try this of course it's not ideal, sorry [main.cdc1.txt](https://github.com/zrax/pycdc/files/13697466/main.cdc1.txt)

Thank you ^^

**Comment by zrax** [comment]
Duplicate #452

**Comment by EgemenErtug** [comment]
hello, @greenozon im tryna crack a code and ive used your 2 patches for jump_backward and some other oppcode, wonder if you patches for this PUSH_EXC_INFO and END_FOR?

**Comment by EgemenErtug** [comment]
also RETURN_GENERATOR

**Comment by greenozon** [comment]
better if you attach some sample pyc files

**Comment by EgemenErtug** [comment]
[example.zip](https://github.com/user-attachments/files/18231578/example.zip)

**Comment by zrax** [comment]
> im tryna crack a code and

This repo is not a help forum for your reverse engineering projects.  The more helpful way to deal with incomplete decompyles and bugs is with an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) demonstrating just the issue and as little else as possible.
