### ISSUE TITLE
Unsupported opcode: BEFORE_WITH

### ISSUE THREAD

**Issue by anandh8x** [zrax/pycdc#410]
Python version is 3.11

When I try to decompile it showing like Unsupported opcode: BEFORE_WITH
And exited with # WARNING: Decompyle incomplete
Please help

**Comment by ThePrainsLive** [comment]
I have a different problem too :/
File: a.pyc (Python 3.11)
Unsupported opcode: PUSH_EXC_INFO

**Comment by greenozon** [comment]
would be good to attach your sample pyc files though...

**Comment by ThePrainsLive** [comment]
> örnek pyc dosyalarınızı eklerseniz iyi olur ...

https://drive.google.com/file/d/1m_5XpBImkNeB5oTZ_uc2bQLe4Xwf4qu4/view?usp=sharing

Source Generated with Decompyle++
File: a.pyc (Python 3.11)
Unsupported opcode: PUSH_EXC_INFO
import time
import selenium
import requests
import random
import json
import string
import os
import re
import locale
import unidecode
import base64

WARNING: Decompyle incomplete

**Comment by ThePrainsLive** [comment]
> @ThePrainsLive çok tuhaf... Bunu dosyanızda buldum, pyc'nizi doğrudan buraya ekleyebilir misiniz? (sadece sürükleyip bırakmanız yeterli)
> 
> Kötü BÜYÜ!
[a.zip](https://github.com/zrax/pycdc/files/13553514/a.zip)

**Comment by anandh8x** [comment]
[f.zip](https://github.com/zrax/pycdc/files/13560051/f.zip)

**Comment by anandh8x** [comment]
@greenozon here the file

**Comment by authrequest** [comment]
Hope we can add this opcode :D I just found this repo and getting the same error on my .pyc
Other opcode is `MAKE_CELL`

Thank you for all your work

**Comment by greenozon** [comment]
@anandh8x 
a poor try... (no try /except, etc)
[mohoe-issue410.cdc1.txt](https://github.com/zrax/pycdc/files/13573134/mohoe-issue410.cdc1.txt)

**Comment by ThePrainsLive** [comment]
@greenozon Did you see the file I sent? 
Is the problem related to me?
thanks.

**Comment by anandh8x** [comment]
> @anandh8x 
> a poor try... (no try /except, etc)
> [mohoe-issue410.cdc1.txt](https://github.com/zrax/pycdc/files/13573134/mohoe-issue410.cdc1.txt)
> 

Nah I actually tried I was on termux ![Screenshot_20231204-211245.png](https://github.com/zrax/pycdc/assets/128164409/8846b269-1e0a-46d4-87e9-85e69cd643d0)

**Comment by anandh8x** [comment]
@greenozon do you know why this happened to me

**Comment by authrequest** [comment]
Can someone add the opcodes for `BEFORE_WITH` ? I wish I could ...but I don't know how

**Comment by authrequest** [comment]
> Can someone add the opcodes for `BEFORE_WITH` ? I wish I could ...but I don't know how [git_issue_sample.zip](https://github.com/zrax/pycdc/files/13591520/git_issue_sample.zip)

@greenozon Do you mind trying?

**Comment by anandh8x** [comment]
> you are using binary that does not yet have a support for missed opcode (as on your screen)
> I did the test locally... 

Can I know how you did that 
So I can do like that as well

**Comment by greenozon** [comment]
@anandh8x   
fork the repo
study python opcodes (docs, sources)
think about needed changes/updates/new piece of code
code it
test it
submit PR
pass PR
we are done :)

**Comment by Imma-P** [comment]
Hello, is there anyone who can help me with this opcode, please? Python version of my pyc file is 3.11 and I can send it with Discord (fredystars94_39712)

**Comment by greenozon** [comment]
pls post your valid telegram id

**Comment by Imma-P** [comment]
> pls post your valid telegram id

Telegram: imma_pro
Discord: fredystars94_39712

**Comment by authrequest** [comment]
@greenozon Can you help me too please! 
Telegram: @EmptyCarts

**Comment by anandh8x** [comment]
> @anandh8x   
> fork the repo
> study python opcodes (docs, sources)
> think about needed changes/updates/new piece of code
> code it
> test it
> submit PR
> pass PR
> we are done :)

@greenozon  I'm not very good with python

Idk how to did that without any errors and done successfully, if you can update the code that would be nice
