### ISSUE TITLE
Error decompyling main.pyc: invalid vector subscript

### ISSUE THREAD

**Issue by aixed** [zrax/pycdc#412]
[main.zip](https://github.com/zrax/pycdc/files/13599625/main.zip)

**Comment by aixed** [comment]
python ver 3.11b4

**Comment by greenozon** [comment]
a poor try to visualize some internals..

[main-issue412.das3.txt](https://github.com/zrax/pycdc/files/13620156/main-issue412.das3.txt)

**Comment by ThePrainsLive** [comment]
> a poor try to visualize some internals..
> 
> [main-issue412.das3.txt](https://github.com/zrax/pycdc/files/13620156/main-issue412.das3.txt)
[a.zip](https://github.com/zrax/pycdc/files/13620198/a.zip)

Please help me too :/

**Comment by discwl** [comment]
@greenozon Can you assist? 

https://github.com/zrax/pycdc/issues/456
