### ISSUE TITLE
Unsupported opcode: POP_JUMP_FORWARD_IF_NONE

### ISSUE THREAD

**Issue by leongwq** [zrax/pycdc#414]
I saw the file in https://github.com/zrax/pycdc/blob/master/bytecode_ops.inl and it is supported. Any idea why I am getting this error?

```python
Unsupported opcode: POP_JUMP_FORWARD_IF_NONE
import os
import gc
import re
import sys
import ast
import pytz
import ctypes
import psutil
import requests
from pathlib import Path
from PyQt5.QtCore import Qt
from dotenv import load_dotenv
from win32api import GetSystemMetrics
from yaml import parser, scanner, safe_load, dump
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont, QPixmap, QMovie, QIcon, QTextCursor
from PyQt5.QtWidgets import QCheckBox, QPushButton, QLineEdit, QVBoxLayout, QLabel, QPushButton, QHBoxLayout, QWidget, QFormLayout, QStackedLayout
from PyQt5.QtCore import Qt, pyqtSignal, QObject, QThread
from telegram import Update
from telegram import error
from telegram.ext import Updater, CommandHandler, CallbackContext
from PIL import Image
from io import BytesIO
```

PYC file: [main.zip](https://github.com/zrax/pycdc/files/13626608/main.zip)

**Comment by greenozon** [comment]
POP_JUMP_FORWARD_IF_NONE  opcode should be handled and processed in a switch/case inside ASTree.cpp module...

even if you try to add empty/fake support there is more heavy issue afterwards:

![image](https://github.com/zrax/pycdc/assets/765343/0a19877e-8e28-4073-8ffc-01cd5b09092e)

**Comment by greenozon** [comment]
Here is my try (well, not full as that issue crashes the processing loop...)

[main-issue414.das1.txt](https://github.com/zrax/pycdc/files/13628168/main-issue414.das1.txt)

**Comment by leongwq** [comment]
> Here is my try (well, not full as that issue crashes the processing loop...)
> 
> [main-issue414.das1.txt](https://github.com/zrax/pycdc/files/13628168/main-issue414.das1.txt)

Wow how did you do it, that's more than what was decompiled. Is it possible to decompile the entire file?

**Comment by greenozon** [comment]
nope, thats all for the moment, at some moment it hit the runtime error (shown on pic above) and crashes

**Comment by zrax** [comment]
Duplicate #452
