### ISSUE TITLE
Error decompyling {file directory}: vector

### ISSUE THREAD

**Issue by anandh8x** [zrax/pycdc#418]
![Screenshot_20231216-215957](https://github.com/zrax/pycdc/assets/128164409/aedfa92d-f0b8-453d-903a-0d728762f5fa)

I have three files which I want to convert to py 
But getting error like shown above

**Comment by greenozon** [comment]
Not enough data to debug by your picture only

**Comment by anandh8x** [comment]
[a.zip](https://github.com/zrax/pycdc/files/13709578/a.zip)
Here's the file @greenozon

**Comment by greenozon** [comment]
@anandh8x 
main issue (multiple cases)
is as follows:

```
Unsupported opcode: RETURN_GENERATOR
```

**Comment by anandh8x** [comment]
There is no solution for it ?

**Comment by greenozon** [comment]
wow, there are much much more unsupported opcodes...
(besides above noted)

**Comment by greenozon** [comment]
there are still many async/with/etc issues but you could get the high level overview of the code

[a.cdc1.zip](https://github.com/zrax/pycdc/files/13720471/a.cdc1.zip)

**Comment by zrax** [comment]
Should be fixed with #462
