### ISSUE TITLE
vector::_M_range_check: __n

### ISSUE THREAD

**Issue by rev1995** [zrax/pycdc#419]
Error decompyling /home/ubuntu/pycdc/main.pyc: vector::_M_range_check: __n (which is 124) >= this->size() (which is 63)

pyc file: https://github.com/redianmarku/Telegram-Member-Adder/blob/main/main.pyc

Can anyone please help. @zrax

**Comment by greenozon** [comment]
this is Python 3.12 which has lots of opcodes to be added ..
so here is very basic try
[main.cdc3.txt](https://github.com/zrax/pycdc/files/13724332/main.cdc3.txt)

**Comment by rev1995** [comment]
@greenozon  thanks a lot man. So this is the source code?

**Comment by greenozon** [comment]
its a kind of source code, just to have basic understanding what's going on

to have 100% valid compilable you have to manually recover code from  das (disassembly) output

**Comment by rev1995** [comment]
@greenozon  thanks man. Much appreciated.

**Comment by Footsiefat** [comment]
@greenozon Please post your patch you did to get it mostly working
