### ISSUE TITLE
invalid vector subscript

### ISSUE THREAD

**Issue by PoLamFe1121** [zrax/pycdc#420]
Unsupported opcode: POP_JUMP_FORWARD_IF_NOT_NONE
Unsupported opcode: BEFORE_WITH
Error decompyling Chrome.pyc: invalid vector subscript

plz help me ToT

my pyc file (Python 3.11.5)
[Chrome.zip](https://github.com/zrax/pycdc/files/13782187/Chrome.zip)

**Comment by greenozon** [comment]
some tries attached

[Chrome.pyc-adv.txt](https://github.com/zrax/pycdc/files/13789018/Chrome.pyc-adv.txt)
[Chrome.pyc-std.txt](https://github.com/zrax/pycdc/files/13789020/Chrome.pyc-std.txt)

**Comment by greenozon** [comment]
wow, the final version of decompiled python file is ....  incredible 873 Megabytes
99% of code are inside  
def normal9()  and
def normal12()

**Comment by KingJunSeong** [comment]
> wow, the final version of decompiled python file is .... incredible 873 Megabytes 99% of code are inside def normal9() and def normal12()

Wow, thank you so much

**Comment by greenozon** [comment]
do you want to take a look? if yes, where should I upload it...

**Comment by KingJunSeong** [comment]
> do you want to take a look? if yes, where should I upload it...
 
It's okay. You don't have to.

**Comment by SSujitX** [comment]
having same issue 

> Unsupported opcode: POP_JUMP_FORWARD_IF_NOT_NONE Unsupported opcode: BEFORE_WITH Error decompyling Chrome.pyc: invalid vector subscript
> 
> plz help me ToT
> 
> my pyc file (Python 3.11.5) [Chrome.zip](https://github.com/zrax/pycdc/files/13782187/Chrome.zip)

# WARNING: Decompyle incomplete

Spring_cleaning.pyc: invalid vector subscript

[Spring_cleaning.zip](https://github.com/zrax/pycdc/files/14185619/Spring_cleaning.zip)
