### ISSUE TITLE
Bad MAGIC! Could not load file [.pyc file]

### ISSUE THREAD

**Issue by steklyashka33** [zrax/pycdc#422]
[pyc_file.zip](https://github.com/zrax/pycdc/files/13834067/pyc_file.zip)

returns an error 
Bad MAGIC! 
Could not load file [.pyc file]

python 3.11
does not work only on version 3.11, but it works on other versions. and it doesn't even work on the test files in the tests folder version 3.11

What to do?

**Comment by greenozon** [comment]
what do you mean under
>does not work only on version 3.11,

please show the output of console and your try
I don't see any troubles with your .pyc files

**Comment by steklyashka33** [comment]
@greenozon

`root@Sergey:~/pycdc# pycdc "./AutoForward_Telegram.pyc"
Bad MAGIC!
Could not load file ./AutoForward_Telegram.pyc
root@Sergey:~/pycdc# pycdc "./test_calls.3.11.pyc"
Bad MAGIC!
Could not load file ./test_calls.3.11.pyc
root@Sergey:~/pycdc# pycdc "./test_calls.3.10.pyc"
# Source Generated with Decompyle++
# File: test_calls.3.10.pyc (Python 3.10)

import sys
import os
sys.stdout.write('Test\n')
sys.stdout.write(os.path.join('foo', 'bar'))
print('\n')
print(eval('4 * 13'))
print()`

**Comment by greenozon** [comment]
not sure whats going on on your PC... sorry
are you using latest bits of the tool? etc

here is what I'm getting on your  input:

[AutoForward_Telegram.pyc.cdc1.txt](https://github.com/zrax/pycdc/files/13854522/AutoForward_Telegram.pyc.cdc1.txt)

**Comment by greenozon** [comment]
abc.pyc is hitting the
Unsupported opcode: DICT_MERGE
issue

but decompiles 99% the rest..

**Comment by steklyashka33** [comment]
@greenozon
could you tell me what needs to be done to properly install pycdc and repeat your success?

**Comment by greenozon** [comment]
for the beginning - build binaries from latest sources?

**Comment by steklyashka33** [comment]
I am using the latest version of pycdc

**Comment by steklyashka33** [comment]
I used this [link ](https://stupin.su/wiki/pycdc/)instruction for linux but I can use windows

**Comment by greenozon** [comment]
the steps in above link IMHO looks over-complicated
I"ve tried to bring up binaries on Linux (Ubuntu 20.04)
and here is my output:

```
git clone  ...
cmake . 
make
 
./pycdc ./AutoForward_Telegram.pyc 
# Source Generated with Decompyle++
# File: AutoForward_Telegram.pyc (Python 3.11)

import os
 
......... (full text shown)
 
 


./pycdc abc.pyc 
# Source Generated with Decompyle++
# File: abc.pyc (Python 3.11)

Segmentation fault (core dumped)
 
 
```

I'm not able to see the crash  under Windows...
