### ISSUE TITLE
# File: main.pyc (Python 3.12)  Unsupported opcode: BEFORE_WITH

### ISSUE THREAD

**Issue by heroofmystory** [zrax/pycdc#426]
I thought it supports that opcode?
Anyone can give me a result skipping the error please?
[main.zip](https://github.com/zrax/pycdc/files/13859952/main.zip)

**Comment by greenozon** [comment]
Unfortunately this pyc gives a hard error like this: (in my case)

![image](https://github.com/zrax/pycdc/assets/765343/ecd67242-3e49-44a2-838e-db7aaa559cc3)

**Comment by 6nz** [comment]
You have to do this by yourself, or you can just crack the keyauth system easily 😂

**Comment by zrax** [comment]
Duplicate #452
