### ISSUE TITLE
cant find __main__ module in pycdc

### ISSUE THREAD

**Issue by rokhare2002** [zrax/pycdc#429]
i am trying to decompile a .os file and after changing name to .pyc, i am running pycdc and facing this error. please advise on what to do next.
![Screenshot_2024-01-31_16-52-30](https://github.com/zrax/pycdc/assets/73052796/9e9c2d8a-f7e2-4759-89ac-aa450e8a5433)

**Comment by greenozon** [comment]
@rokhare2002   pycdc is executable binary
run it directly
