### ISSUE TITLE
Error decompyling deobs_mine.pyc: vector::_M_range_check: __n (which is 10) >= this->size() (which is 7)

### ISSUE THREAD

**Issue by shoaibhassan0** [zrax/pycdc#430]
[deobs_mine.zip](https://github.com/zrax/pycdc/files/14165530/deobs_mine.zip)
i am also attaching this pyc file 
i am using command pycdc -c -v 3.11 deobs_mine.pyc 
on windows 10
When i was decompiling the python marshal object bytecode it results this

E:\build>pycdc -c -v 3.11 deobs_mine.pyc
# Source Generated with Decompyle++
# File: deobs_mine.pyc (Python 3.11)

import requests
import json
import time
import sys
from platform import system
import os
import subprocess
import http.server as http
import socketserver
import threading
from datetime import datetime
import uuid
html_content = '\n<!DOCTYPE html>\n<html>\n<head>\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>H╠│E╠│T╠│T╠│E╠│R╠│ K╠│I╠│ B╠│H╠│E╠│N╠│ K╠│A╠│ B╠│H╠│O╠│S╠│D╠│A╠│ F╠│A╠│D╠│N╠│E╠│ W╠│A╠│L╠│A╠│ S╠│E╠│R╠│V╠│E╠│R╠│</title>\n    <style>\n        body {\n            background-image: url(\'rashmika.jpg\');\n            background-size: cover;\n        }\n    </style>\n</head>\n<body>\n    <h1 style="color: lime;">H╠│E╠│T╠│T╠│E╠│R╠│ K╠│I╠│ B╠│H╠│E╠│N╠│ K╠│A╠│ B╠│H╠│O╠│S╠│D╠│A╠│ F╠│A╠│D╠│N╠│E╠│ W╠│A╠│L╠│A╠│ S╠│E╠│R╠│V╠│E╠│R╠│</h1>\n    <p style="color: cyan;">This server created by Tera papa≡ƒÑ╖</p>\n    \n    <p style="color: olive;">Owner Name ::- ≡ƒö¿iTs  Me≡ƒÑé</p>\n    \n    <p style="color: lime;"> ________All Done....Loading......</p>\n    <ul>\n        <li style="color: cyan;">1. ≡¥Ö╖≡¥ÜÄ≡¥Ü¥≡¥Ü¥≡¥ÜÄ≡¥Ü¢≡¥Ü£ ≡¥ÜÄ≡¥Üƒ≡¥ÜÄ≡¥Ü¢≡¥Üó≡¥Ü¥≡¥ÜÆ≡¥Üû≡¥ÜÄ ≡¥Üî≡¥Ü¢≡¥Üó≡¥ÜÆ≡¥Üù≡¥ÜÉ ≡ƒÿé </li>\n        <li style="color: purple;">2. if You think your bad i am your dad </li>\n        <li style="color: cyan;">3. <=================> </li>\n        <li style="color: cyan;">4. Call me brother ≡ƒÖà </li>\n        <li style="color: cyan;">5. EVERYONE</li>        \n    </ul>\n\n    <audio controls autoplay loop>\n        <source src="https://pagalsong.in/download/14337/I%20Love%20You%20128%20KBPS%20mp3" type="audio/mpeg">\n        Your browser does not support the audio element.\n    </audio>\n</body>\n</html>\n'

class MyHandler(http.server.SimpleHTTPRequestHandler):

    def do_GET(self):
Error decompyling deobs_mine.pyc: vector::_M_range_check: __n (which is 10) >= this->size() (which is 7)

**Comment by shoaibhassan0** [comment]
> Please recheck your attachment deobs_mine.zip it shows the
> 
> ```
> Bad MAGIC!
> ```
> 
> when try to use with pycdas or pycdc
first unzip it 
Its marshal object bytecode i used parameters 

<p>pycdc -c -v 3.11 deobs_mine.pyc </p>
it is compiled with 3.11 so i used 3.11 here

**Comment by shoaibhassan0** [comment]
@greenozon
I see your comment i another issue of this pycdc you changed or modified some source of pycdc and then compile it which bypasses the error like i now experienced can you tell these changes

**Comment by shoaibhassan0** [comment]
@greenozon

**Comment by shoaibhassan0** [comment]
I tested many times and now i have found that when this situation meets 
        if(opcode == 146 && operand == 10 && pos == 164){
                fprintf(stderr,"Error: Occuring...");
             }
the program return error but skipping this work..
        if(opcode == 146 && operand == 10 && pos == 164){
                fprintf(stderr,"Error: Occuring...");
                 continue;
             }

**Comment by greenozon** [comment]
this is strange, but you hint helped to move forward
```
pycdc -c -v 3.11 deobs_mine.pyc
```

attached a try to decompile it ... (not ideal of course)
[deobs_mine.cdc.txt](https://github.com/zrax/pycdc/files/14181017/deobs_mine.cdc.txt)

**Comment by shoaibhassan0** [comment]
Thanks a lot @greenozon can you give me the modified version of pycdc you are using. So we should request for pull request.

**Comment by greenozon** [comment]
not that easy
I"ve plenty of changes and I've a plan to create some PRs one by one
for the moment there is one outstanding, if you wish you could help to move it forward
https://github.com/zrax/pycdc/pull/411

**Comment by zrax** [comment]
Should be fixed with #462
