### ISSUE TITLE
Error decompyling vector::_M_range_check: __n (which is 16) >= this->size() (which is 11)

### ISSUE THREAD

**Issue by RandomStrangerOnTheInternet** [zrax/pycdc#431]
When decompiling a Python 3.11 `.pyc` file I receive the following errors, would there be a possibility to 'ignore' these opcodes and to decompile the rest of the code anyways?

I've tried to fix the `JUMP_BACKWARD` based off some recommendations here, however I'm now running into the following issues:
```
Unsupported opcode: MAKE_CELL
...
Warning: block stack is not empty!
...
Error decompyling ../Analysis.pyc: vector::_M_range_check: __n (which is 16) >= this->size() (which is 11)
```

[Analysis.zip](https://github.com/zrax/pycdc/files/14184556/Analysis.zip)

Any help would be greatly appreciated!

**Comment by shoaibhassan0** [comment]
I try to decompile as much as possible for you check it.
[Analysis.pyc.txt](https://github.com/zrax/pycdc/files/14184943/Analysis.pyc.txt)

**Comment by greenozon** [comment]
Another option
still not ideal (check the None across the module)

[Analysis-issue431.cdc1.txt](https://github.com/zrax/pycdc/files/14185050/Analysis-issue431.cdc1.txt)

**Comment by RandomStrangerOnTheInternet** [comment]
It's better then nothing, thanks a lot for the help!

**Comment by greenozon** [comment]
could be closed if we happy to live with it? :)

**Comment by zrax** [comment]
This is not a place for exchanging decompyles.
