### ISSUE TITLE
 Error decompyling deobs_mine.pyc: std::bad_cast.

### ISSUE THREAD

**Issue by shoaibhassan0** [zrax/pycdc#432]
I have experience an exception when decompiling pyc marshal object bytecode. with these parameters below. here i use 3.9 because marshal bytecode is python3.9 bytecode.
     pycdc -c -v 3.9 deobs_mine.pyc
I know the source code of this compiled but how I bypass this exception to continue decompiling     
     
     E:\build>pycdc -c -v 3.9 deobs_mine.pyc
    # File: deobs_mine.pyc (Python 3.9)
    foo = False
    if foo:
          Error decompyling deobs_mine.pyc: std::bad_cast
          
          
          
Also error occurs when..
opcode == 45 and   operand == 0     and pos == 28

NOTE: 45 opcode is RETURN_VALUE

i used it check when error occurs in ASTree.cpp
         if(opcode == 45 && operand == 0 && pos == 28){
             fprintf(stderr, "opcode: %s\n", Pyc::OpcodeName(opcode & 0xFF));
              fprintf(stderr,"Error: Occuring...");
         }
         
         
And attachment file is there.
.

[deobs_mine.zip](https://github.com/zrax/pycdc/files/14185083/deobs_mine.zip)

**Comment by greenozon** [comment]
THere is just one location in the code that might throw the nasty std::bad_cast exception..

this is very unfortunately I'd say
never seen it before

**Comment by greenozon** [comment]
btw, pycdas was able to show opcodes though...

```
    [Disassembly]
        0       LOAD_CONST                    0: False
        2       STORE_NAME                    0: foo
        4       LOAD_NAME                     0: foo
        6       POP_JUMP_IF_FALSE             16
        8       LOAD_CONST                    1: 1
        10      LOAD_CONST                    2: 0
        12      MAKE_FUNCTION                 33
        14      STORE_NAME                    1: bar
        16      LOAD_NAME                     2: print
        18      LOAD_CONST                    3: 'hi! Bro'
        20      CALL_FUNCTION                 1
        22      POP_TOP
        24      LOAD_CONST                    4: None
        26      RETURN_VALUE
```

**Comment by shoaibhassan0** [comment]
Bro, @greenozon very very thanks.
I know the **pycdas** does it's job but **pycdc** is causing error why it shows error.
Is there anyway to bypass it.
I want to bypass it to continue to decompiling code.

**Comment by Mhordx** [comment]
Is there a perfect workaround？
