### ISSUE TITLE
Unsupported opcode: INSTRUMENTED_POP_JUMP_IF_TRUE

### ISSUE THREAD

**Issue by JayCroghan** [zrax/pycdc#434]
Please add.

**Comment by greenozon** [comment]
You could do it yourself!
hints:
ASTree.cpp
find all refs to existing supported opcode

Pyc::POP_JUMP_IF_TRUE_A

and add nearby your lovely INSTRUMENTED one!

**Comment by JayCroghan** [comment]
As soon as I edit python_3_12.cpp to add the op code Visual Studio starts giving me loads of errors. Do I need to run CMake again or something?

**Comment by JayCroghan** [comment]
![Uploading not implemented.png…]()

**Comment by JayCroghan** [comment]
<img width="541" alt="not implemented" src="https://github.com/zrax/pycdc/assets/1171148/1c83264f-52d2-4480-b648-9a0d8856c3d3">

**Comment by greenozon** [comment]
Looks like you are stepping the dangerous way!

you are editing auto-generated file, look up the 1st line of it:

```
/* This file was auto-generated with comp_map.py.  DO NOT EDIT! */
```

**Comment by zrax** [comment]
Duplicate #453
