### ISSUE TITLE
 Unsupported opcode: JUMP_BACKWARD

### ISSUE THREAD

**Issue by VB-HaCKer** [zrax/pycdc#435]
[main.zip](https://github.com/zrax/pycdc/files/14230050/main.zip)

**Comment by greenozon** [comment]
try this output...

[main-issue435.cdc1.txt](https://github.com/zrax/pycdc/files/14230454/main-issue435.cdc1.txt)

**Comment by zrax** [comment]
This is not a place for exchanging decompiles.
