### ISSUE TITLE
Error decompyling Serialchecker.pyc: vector::_M_range_check: __n (which is 24) >= this->size() (which is 22)

### ISSUE THREAD

**Issue by Myamii** [zrax/pycdc#439]
[Serialchecker.zip](https://github.com/zrax/pycdc/files/14319909/Serialchecker.zip)

i cant decompile it Error decompyling Serialchecker.pyc: vector::_M_range_check: __n (which is 24) >= this->size() (which is 22)

Python Version 3.12

**Comment by greenozon** [comment]
some try, also following cases hit during process:

Warning: Stack history is not empty!
Warning: block stack is not empty!
Warning: block stack is not empty!
Warning: block stack is not empty!
Unsupported opcode: LOAD_SUPER_ATTR
Warning: Stack history is not empty!
Warning: block stack is not empty!
[Serialchecker.cdc1.txt](https://github.com/zrax/pycdc/files/14322067/Serialchecker.cdc1.txt)

**Comment by Myamii** [comment]
> some try, also following cases hit during process:
> 
> Warning: Stack history is not empty! Warning: block stack is not empty! Warning: block stack is not empty! Warning: block stack is not empty! Unsupported opcode: LOAD_SUPER_ATTR Warning: Stack history is not empty! Warning: block stack is not empty! [Serialchecker.cdc1.txt](https://github.com/zrax/pycdc/files/14322067/Serialchecker.cdc1.txt)

thanks!

**Comment by zrax** [comment]
Should be fixed with #462
