### ISSUE TITLE
cant decompile this file

### ISSUE THREAD

**Issue by Myamii** [zrax/pycdc#442]
[main.zip](https://github.com/zrax/pycdc/files/14322615/main.zip)

**Comment by Myamii** [comment]
(its with pyarmor obfuscated but i think i already deobfuscated it )

**Comment by ddouworld** [comment]
I don't think pycdc would decompile properly if it had been confused with pyarmor

**Comment by greenozon** [comment]
of course not :)
pyarmor is very sophisticated protector
just imagine if opcode values are changed and instead of  say LOAD_CONST you hit the STORE_NAME :)

**Comment by zrax** [comment]
pycdc does not support obfuscated .pyc files
