### ISSUE TITLE
Error decompyling lcu.pyc: vector::_M_range_check: __n (which is 62) >= this->size() (which is 61)

### ISSUE THREAD

**Issue by flyingwr** [zrax/pycdc#443]
[lcu.zip](https://github.com/zrax/pycdc/files/14330736/lcu.zip)

Python 3.12

**Comment by greenozon** [comment]
not perfect, some try..
[lcu-issue443.cdc1.txt](https://github.com/zrax/pycdc/files/14334745/lcu-issue443.cdc1.txt)

**Comment by zrax** [comment]
Should be fixed with #462
