### ISSUE TITLE
connector.pyc: invalid vector subscript

### ISSUE THREAD

**Issue by NevermindNilas** [zrax/pycdc#444]
Hi, I am trying to decompile the following pyc files, I get the invalid vector error for connector.pyc and a " deoompyle incomplete " warning for struct.pyc

Here's the zip file, I would appreciate any help.

[extracted.zip](https://github.com/zrax/pycdc/files/14341189/extracted.zip)

**Comment by greenozon** [comment]
for struct.pyc:

```
# File: struct-issue444.pyc (Python 3.12)

__all__ = [
    'calcsize',
    'pack',
    'pack_into',
    'unpack',
    'unpack_from',
    'iter_unpack',
    'Struct',
    'error']
import _struct
from _struct import _clearcache
from _struct import __doc__

```

**Comment by NevermindNilas** [comment]
Hi, don't sweat it, I have found an amazing tool online that did the decompilation near perfectly. Thank you very much!

**Comment by greenozon** [comment]
good luck, pls close the ticket then
