### ISSUE TITLE
Eror in Pyc python 3.11

### ISSUE THREAD

**Issue by codes-team** [zrax/pycdc#457]
# Source Generated with Decompile++
# File: dec.pyc (Python 3.11)

[1]    21533 segmentation fault  pycdc dec.pyc

i try pycdas and i got 100% code recover but it's hard to format code into original code like pycdc do so how can i upgrade pycdc to decompile pyc python3.11

**Comment by greenozon** [comment]
easy
ref to #452 and implement missed opcodes!

**Comment by codes-team** [comment]
> easy
> ref to #452 and implement missed opcodes!
> 

so how can i get thia opcodes
