### ISSUE TITLE
Unsupported opcode: RETURN_GENERATOR

### ISSUE THREAD

**Issue by Bhattistar** [zrax/pycdc#459]
Half code is decompiled and half is not returning error
Unsupported opcode: RETURN_GENERATOR
And for one code it returned BAD MAGIC but that was a bytecode

**Comment by Bhattistar** [comment]
[v.txt](https://github.com/zrax/pycdc/files/14413664/v.txt)
This is output

**Comment by zrax** [comment]
Duplicate #452
