### ISSUE TITLE
Unsupported opcode: POP_JUMP_BACKWARD_IF_TRUE

### ISSUE THREAD

**Issue by kvanbiesen** [zrax/pycdc#461]
Something weird,

when trying to decompile a prjects, i get this error. (3.11)

But i clearly see the Opcode mentioned in the bytecode_ops.inl.

tried compiling multiple times but it doesnt seem to pick this one up for some reason?

**Comment by kvanbiesen** [comment]
Never mind; missed the checkmark in the box bove the ASTREE implementation. Will wait

**Comment by zrax** [comment]
Duplicate #452
