### ISSUE TITLE
sorry for this issue i try to solve some pycdc problem

### ISSUE THREAD

**Issue by codes-team** [zrax/pycdc#474]
# Source Generated with Decompyle++
# File: amer.cpython-311.pyc (Python 3.11)

Unsupported opcode: BEFORE_WITH
import os
amer = "print('Hello World')"
x = 0
x = x + 1
# WARNING: Decompyle incomplete

i solve some problem from Solutions i see in The other issues like Segmentation fault thanks for You always provide a solution and I know that the opcode for the new Python is different and very strange but There is currently nothing better than pycdc to decompile pyc files so i hope You are able to upgrade it to support Python 3.11.8 like pycdas thank you❤

**Comment by TiZCrocodile** [comment]
as you can see in #452 there is already an issue opened about the unsupported `BEFORE_WITH` opcode, so this is a duplicated issue, but anyways thank you for your patience, I also think that pycdc is the best in its field.

**Comment by zrax** [comment]
Duplicate #452

**Comment by S4HIL09** [comment]
# Source Generated with Decompyle++

# File: out.pyc (Python 3.11)

Segmentation fault


Please solve this problem

**Comment by greenozon** [comment]
please attach your .pyc file that lead to segfault
thx

**Comment by S4HIL09** [comment]
Bro tell me segfault which one is it

**Comment by S4HIL09** [comment]
I am worried about this since many days, please help me bro

**Comment by greenozon** [comment]
https://en.wikipedia.org/wiki/Segmentation_fault
