### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by isaka-james** [zrax/pycdc#480]
This got the very poor documentation if someone is new here, can't even know how to use it. Please consider making a better readme or somewhere where you defined how to use this.

I came here because `uncompyle6` doesn't work with python3.11 ,  and I am struggling to find resources to help understand how to use this!

**Comment by greenozon** [comment]
there are 2 tools
pycdas - prints python opcodes
pycdc  - prints decompiled source

example usage:

```
pycdas sample.cpython-312.pyc
pycdc sample.cpython-312.pyc
```

**Comment by isaka-james** [comment]
Got you but you gotta update the readme
