### ISSUE TITLE
when did you post,3.11 bro

### ISSUE THREAD

**Issue by salarasm** [zrax/pycdc#491]
we need it

**Comment by TheHellTower** [comment]
https://github.com/zrax/pycdc/commit/9f1d0f2a212872e71f2a372f2f6f5f813eda07dd
https://github.com/zrax/pycdc/commit/a6de2209fcfce7374c01e398bd0764c76aa9eb40
https://github.com/zrax/pycdc/commit/035f963f3d36c2785cd7cfc26480f63917991a07
https://github.com/zrax/pycdc/commit/ee934a1e993f4a57e5875375718a0509fd0c51ac
https://github.com/zrax/pycdc/commit/409f17582779fc4792d20a7f9e0a8b2862f3b797

**Comment by TheHellTower** [comment]
If you have an issue please describe it instead with a sample file.
