### ISSUE TITLE
will it support decompiling .pyd file where i build that using c/c++

### ISSUE THREAD

**Issue by tamil-12** [zrax/pycdc#502]

**Comment by greenozon** [comment]
as far as I understandd  .pyd are the executable binaries if we talk Windows they are like .dll files
so the answer is no I believe, py -> pyc are totally different flow, sorry

**Comment by zrax** [comment]
That's correct, .pyd files are native code.  You'll have better luck using tools for native executables (IDA Pro, Ghidra, etc).
