### ISSUE TITLE
missing op maps for 3.11 and 3.12, comments for "initial 3.13 support" misidentify some 3.11/3.12 ops as "3.13 ->" ops

### ISSUE THREAD

**Issue by wilson0x4d** [zrax/pycdc#509]
i'm a new pycdc user, but it looks really promising and i like the approach of the code.

that said, as part of some other work i am doing i did a review of cpython 3.9, 3.10, 3.11, 3.12, and 3.13 source code vs. the current pycdc code and noticed some of the newly added "initial 3.13 support" opcodes actually appeared in 3.11 and 3.12. i also found that 3.11 and 3.12 op maps are missing entries.. maybe a dozen or so opcodes each. the 3.9, 3.10 and 3.13 op maps lgtm though, but i personally need(ed) accurate 3.11 and then 3.12 op maps for successful/clean pycdas results.

i have pushed a draft of my edits to a fork, these edits have allowed me to decompile the python std lib from 3.11 and 3.12 with 8 or so unique "unsupported opcode" errors, and, i can get clean pycdas results from the project i am reversing.

is there someone that can have a look and work with me to help me understand the codebase a little better? specifically:

1. i'm not entirely sure when to use OPCODE vs OPCODE_A, i understand the purpose of _A but I don't see that it makes any difference to my testing. I could use some help understanding how to decide (or how to research) which to use.
2. i could use some help understanding the test process to make sure tests pass. i ran the python std lib through `compileall` and have essentially thrown the entirety of python's library at pycdc/pycdas to suss out problems, while this "works on my machine" I doubt this is sufficient for getting a PR submitted.
3. i would like some guidance on if/how to tackle AST changes. I am able to get some really good results from `pycdas` but there seems to be some gaps with `pycdc` and I believe this is because the `ASTree.cpp` needs some updates (i think for about 3 dozen opcodes) -- i lack the experience to really handle that on my own and could use some guidance.
4. i'm certain i've made a mess of `bytecode_ops.inl` -- someone with experience could tell me where i went wrong and how to organize/add/remove my edits.

i don't want to PR what i have, i would like to iterate, clean it up, and submit a final commit for a PR later.

draft edits are at; https://github.com/wilson0x4d/pycdc/tree/py311_py322_draft 

what i have works for my needs i'm just trying to help what looks like a good FOSS project progress a little bit while i'm passing through.

thanks!

**Comment by zrax** [comment]
Hmm, upon looking closer, it looks like these specialized opcodes never actually make it into the compiled object anyway -- they're replaced at run-time for performance optimizations.  That means the better approach would be to remove them from 3.13 as well.

**Comment by zrax** [comment]
Should be resolved now with 19f8372358b987fc3fd6c869923bf5cb9846898d
