### ISSUE TITLE
Unsupported opcode: BEFORE_WITH

### ISSUE THREAD

**Issue by huanglin-github** [zrax/pycdc#520]
[main.zip](https://github.com/user-attachments/files/17096448/main.zip)

**Comment by greenozon** [comment]
could you recheck your link please?

**Comment by huanglin-github** [comment]
> could you recheck your link please?
alright

**Comment by zrax** [comment]
This repo is not a help forum for your reverse engineering projects.  The more helpful way to deal with incomplete decompyles and bugs is with an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) demonstrating just the issue and as little else as possible.
