### ISSUE TITLE
how to read that result of decompile

### ISSUE THREAD

**Issue by meopeongokngheck** [zrax/pycdc#524]
[obf-6467646652.zip](https://github.com/user-attachments/files/17433823/obf-6467646652.zip)
help me please

**Comment by greenozon** [comment]
the tools in this repo handles .pyc files
you provided plain text .py module
what is your question about then?

**Comment by greenozon** [comment]
I believe the tools in this repo does not solve the readability issues, sorry
you need to find some tool simlar like de4dot for .net world that is capable of renaming symbols..
