### ISSUE TITLE
Unsupported opcode: BEGIN_FINALLY

### ISSUE THREAD

**Issue by avrdasm** [zrax/pycdc#526]
pycdc.exe ursServer.pyc
Unsupported opcode: BEGIN_FINALLY (97)
Unsupported opcode: BEGIN_FINALLY (97)
Unsupported opcode: BEGIN_FINALLY (97)
Unsupported opcode: BEGIN_FINALLY (97)
Unsupported opcode: BEGIN_FINALLY (97)
Warning: Stack history is not empty!
Warning: block stack is not empty!
Error decompyling ursServer.pyc: std::bad_cast
[ursServer.zip](https://github.com/user-attachments/files/17539582/ursServer.zip)

**Comment by zrax** [comment]
Duplicate #449
