### ISSUE TITLE
python 3.9 pyc Decompilation error

### ISSUE THREAD

**Issue by Stella-sea** [zrax/pycdc#527]
https://drive.google.com/file/d/1EsXXuiQnxgNgGJ6HOFOuTmo1J9eKJyrO/view?usp=sharing
This is the address of my main.pyc, and after trying the #253 solution it did achieve avoiding the unsupported opcode error, but after continuing the decompilation process, I encountered a new problem, Warning: Stack history is not empty! and Warning: block stack is not empty!Warning: Stack history is not empty!
![main pyc](https://github.com/user-attachments/assets/5ed42c5a-876f-4aa1-83d6-9597ef80ea70)

**Comment by greenozon** [comment]
253 does not have any solution

**Comment by Stella-sea** [comment]
Sorry, let me describe the process a bit more concretely, after I first used pycdc to decompile it, the error given was Unsupported opcode: RERAISE, then I managed to find a solution in issues: #Decompyle incomplete - Python 3.9 please help #253 [https://github.com/zrax/pycdc/issues/253], by adding the last part of [raymondren1982], I encountered the current error with the newly compiled pycdc.exe: "Warning: block stack is not empty!Block stack is not empty! Warning: Stack history is not empty!", and now I still don't know how to fix it.

**Comment by zrax** [comment]
This repo is not a help forum for your reverse engineering projects.  The more helpful way to deal with incomplete decompyles and bugs is with an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) demonstrating just the issue and as little else as possible.
