### ISSUE TITLE
python 3.12 pyc error Please help 

### ISSUE THREAD

**Issue by z6189949** [zrax/pycdc#528]
https://drive.google.com/file/d/1AiV5HDQ5gTVwyiF6i0fV_kQCv29kajAc/view?usp=sharing

class AutoBuyer(QMainWindow):
Unsupported opcode: MAKE_CELL (225)
    pass
# WARNING: Decompyle incomplete   
I lost my code Please help me

**Comment by greenozon** [comment]
check this out
[main_528.cdc3.txt](https://github.com/user-attachments/files/17882204/main_528.cdc3.txt)

**Comment by z6189949** [comment]
Please tell me why I failed THANKS

> 看看这个 [main_528.cdc3.txt](https://github.com/user-attachments/files/17882204/main_528.cdc3.txt)

**Comment by zrax** [comment]
This repo is not a help forum for your reverse engineering projects.  The more helpful way to deal with incomplete decompyles and bugs is with an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) demonstrating just the issue and as little else as possible.
