### ISSUE TITLE
Support new opcodes decompilation

### ISSUE THREAD

**Issue by jsrcode** [zrax/pycdc#530]
BINARY_SLICE 
BEFORE_WITH 
PUSH_EXC_INFO 
LOAD_ASSERTION_ERROR 
COPY 
RETURN_GENERATOR
MAKE_CELL  
LOAD_FAST_AND_CLEAR 
CALL_INTRINSIC_1
DICT_MERGE
CALL_FUNCTION_EX

**Comment by zrax** [comment]
Duplicate (see #498, #453, etc)
