### ISSUE TITLE
pycdc crashes, any tutorial to trace where is the problem

### ISSUE THREAD

**Issue by retsyo** [zrax/pycdc#68]
when I run pycdc on some pyc, pycdc crashes. So is there any guide to find which cause this problem, and then we can fix it. I know we can debug the C source file, but it is some difficult for C newbie. So if there some way can aid debug, it will be good for this project and the user. Thanks

**Comment by mancoast** [comment]
Upload the pyc file or the corresponding Python code and let's take a look.

**Comment by retsyo** [comment]
hi, sir
all the 3 pyc files in
http://www.msbsoftware.it/microrender/data/MicroRenderDemo17.zip crash
pycdc.
thanks

2015-11-17 2:21 GMT+08:00, mancoast <notifications@github.com>:
> Upload the pyc file or the corresponding Python code and let's take a look.
>
>

**Comment by zrax** [comment]
This looks like licensed code, based on comments in the Readme and __init__.py files.  Please do not post requests for support in reverse engineering code you do not have a license to the source for.

**Comment by retsyo** [comment]
I don't mean to post it public, how can I edit my previous post?
