### ISSUE TITLE
pycdc coredump

### ISSUE THREAD

**Issue by JeanLeezh** [zrax/pycdc#74]
FILE: ASTree.cpp, 
FUNCTION: PycRef<ASTNode> BuildFromCode(PycRef<PycCode> code, PycModule\* mod)
LINE: 1219
REASON: empty stack_hist cause stack_hist.top() core.

**Comment by ReDucTor** [comment]
Need source (and python compiler version) or pyc to work out the cause of this.

**Comment by zrax** [comment]
Closing due to lack of response.
