### ISSUE TITLE
No releases yet

### ISSUE THREAD

**Issue by ALTracer** [zrax/pycdc#82]
Your Python Decompiler is awesome! At least works for me on python2.2 generated ancient .pyc files.

I am currently struggling to port the CASIO IDES waveconverter (synth patch compressor) on Linux. Fortunately, it is a py2exe PE containing all the .py/.pyc. With your handy tool, the interface (wxWidgets) got working on my LinuxMint 17.2 x64 (yet there are .pyd libraries).

However, I had to `$git clone $cmake $make` just to run the $pycdc for the first time. Why don't you create some **Releases with binary files** on GitHub? That would be easier for some people, if, say, they wanted to just decompyle a bunch of .pyc. (I even found out I had no CMake in the system)

**Comment by zrax** [comment]
pycdc/pycdas are advanced developer tools, and there have been no stable releases so far.  As such, it is expected that users will be able to compile it from source for now.  Furthermore, when talking about Linux, there are many different distributions to consider, even though pycdc has minimal dependencies.  Therefore, I'd say this is currently out of scope.  Perhaps there will be binary releases some day, but not before a lot of work towards making a stable production release is done.
