### ISSUE TITLE
Decompiler generates "import random" without usage

### ISSUE THREAD

**Issue by CrazyPython** [zrax/pycdc#89]
Here's the pyc file: [encode.pyc](https://github.com/zrax/pycdc/files/428554/encode.txt)

I renamed it to txt so GitHub could accept it. Rename it to pyc.

Decompiling generates an unused `import random`.

**Comment by CrazyPython** [comment]
It also generates `lambda .0` and a continue statement inside a lambda.

**Comment by zrax** [comment]
It appears your file is corrupt...  What would be better is to post the source and the Python version that compiled it, so the round-trip can be verified/corrected.

**Comment by CrazyPython** [comment]
@zrax sorry, it's for CTF. Guess to head back to wireshark and get another go at it... But shouldn't a warning be printed?

**Comment by zrax** [comment]
It does print a warning -- that's how I know it's corrupt:
```
CreateObject: Got unsupported type 0x3D
```
