### ISSUE TITLE
What python versions does pycdc support?

### ISSUE THREAD

**Issue by Jo0go** [zrax/pycdc#90]
What python versions does pycdc support?

**Comment by zrax** [comment]
It currently supports bytecode from Python 1.0 - Python 3.5 stable releases.  Python 3.6a4 is also supported in bytecode, but the bytecode is subject to change before 3.6 is released.

However, bytecode support only means that we can disassemble it (pycdas).  The level of actual support may vary by Python version, as some newer features are not fully supported (or supported at all in some cases) by the AST generator yet.
