### ISSUE TITLE
Unsupported opcode: <255> .pyc Python2.7

### ISSUE THREAD

**Issue by alkoforumm** [zrax/pycdc#98]
Command:
`pycdc.exe C:\****\sricpt.pyc`

Output:
```
# Source Generated with Decompyle++
# File: srcipt.pyc (Python 2.7)

Unsupported opcode: <255>
pass
# WARNING: Decompyle incomplete
```

I attached the file inside zip here..
[script.zip](https://github.com/zrax/pycdc/files/546560/script.zip)
Second different file but same error..
[script2.zip](https://github.com/zrax/pycdc/files/546577/script2.zip)

Any thing that I can do about this issue ?
A helpfull link that I maybe found.. https://net.cs.uni-bonn.de/fileadmin/ag/martini/projekte/StudentCTF/hacklu2013-internals-whatswrongwiththis.pdf

Command:
`pycdas.exe C:\****\sricpt.pyc`

Output:
```
[Code]
    File Name: sricpt
    Object Name: <pjorion_protected>
    Arg Count: 0
    Locals: 0
    Stack Size: 10
    Flags: 0x00000040 (CO_NOFREE)
    [Names]
        '__builtin__'
        'sys'
        'zlib'
        'marshal'
        'reload'
        'loads'
        'join'
        'decompress'
        '_getframe'
        'f_code'
        'co_code'
        'len'
        'dir'
        'x'
        'chr'
        'int'
        'bin'
        'ord'
        'rjust'
        'globals'
    [Var Names]
    [Free Vars]
    [Cell Vars]
    [Constants]
        -1
        None
        ''
        1
        2
        8
        '0'
    [Disassembly]
        0       SETUP_EXCEPT            72461 (to 72467)
        6       <INVALID>
        7       <INVALID>
        8       <INVALID>
        9       STORE_GLOBAL
```

It display this and then it crash's.

**Comment by zrax** [comment]
This file has been intentionally obfuscated with pjorion, which is well beyond the scope of what Decompyle++ is designed to provide.
